sequenceDiagram
  participant participant_getParadoxDocTag as getParadoxDocTag
  participant participant_isParadoxDocTagName as isParadoxDocTagName
  participant_isParadoxDocTagName->>participant_getParadoxDocTag: getParadoxDocTag()
  participant_getParadoxDocTag-->>participant_isParadoxDocTagName: return
