import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

import { expect, test } from 'bun:test';

import { analyze } from '../src/analyze/analyze.js';
import type { ParadoxConfig } from '../src/config/types.js';
import { buildModel } from '../src/model/buildModel.js';
import { render } from '../src/render/render.js';
import { write } from '../src/write/write.js';

test('keeps donation support disabled when config is undefined', async () => {
  const root = await createFixtureAsync();
  try {
    const { analysis, result } = await renderFixtureAsync(root);
    expect(analysis.donation).toBeNull();
    expect(result.fundingYaml).toBeNull();
    expect(result.readme).not.toContain('## Donation');
    expect(result.indexHtml).not.toContain('<h2>Donation</h2>');
  } finally {
    await rm(root, { force: true, recursive: true });
  }
});

test('renders canonical donation outputs from one account', async () => {
  const root = await createFixtureAsync();
  try {
    const { analysis, result } = await renderFixtureAsync(root, 'ankhorage');
    expect(analysis.donation).toEqual({ account: 'ankhorage' });
    expect(result.fundingYaml).toBe(
      '# Generated by Paradox. Do not edit manually.\ngithub: ankhorage\n',
    );
    expect(result.readme).toContain('## Donation');
    expect(result.readme).toContain('[Support @ankhorage](https://github.com/sponsors/ankhorage)');
    expect(result.indexHtml).toContain('href="https://github.com/sponsors/ankhorage"');
  } finally {
    await rm(root, { force: true, recursive: true });
  }
});

test('rejects invalid configured donation accounts', async () => {
  const root = await createFixtureAsync();
  try {
    await expect(renderFixtureAsync(root, 'invalid account')).rejects.toThrow(
      'Invalid donation account',
    );
  } finally {
    await rm(root, { force: true, recursive: true });
  }
});

test('writes the GitHub funding file in write mode', async () => {
  const root = await createFixtureAsync();
  try {
    const { config, result } = await renderFixtureAsync(root, 'ankhorage');
    await write(result, config, { packageRoot: root, outputRoot: join(root, 'paradox') });
    const funding = await readFile(join(root, '.github', 'FUNDING.yml'), 'utf-8');
    expect(funding).toBe(result.fundingYaml);
  } finally {
    await rm(root, { force: true, recursive: true });
  }
});

test('refuses to overwrite a user-owned funding file', async () => {
  const root = await createFixtureAsync();
  try {
    await mkdir(join(root, '.github'), { recursive: true });
    const fundingPath = join(root, '.github', 'FUNDING.yml');
    await writeFile(fundingPath, 'github: someone-else\n');
    const { config, result } = await renderFixtureAsync(root, 'ankhorage');
    await expect(
      write(result, config, { packageRoot: root, outputRoot: join(root, 'paradox') }),
    ).rejects.toThrow('Refusing to overwrite existing non-Paradox');
    expect(await readFile(fundingPath, 'utf-8')).toBe('github: someone-else\n');
  } finally {
    await rm(root, { force: true, recursive: true });
  }
});

test('removes a Paradox-owned funding file when donation is disabled', async () => {
  const root = await createFixtureAsync();
  try {
    const enabled = await renderFixtureAsync(root, 'ankhorage');
    await write(enabled.result, enabled.config, {
      packageRoot: root,
      outputRoot: join(root, 'paradox'),
    });
    const disabled = await renderFixtureAsync(root);
    await write(disabled.result, disabled.config, {
      packageRoot: root,
      outputRoot: join(root, 'paradox'),
    });
    await expect(readFile(join(root, '.github', 'FUNDING.yml'), 'utf-8')).rejects.toThrow();
  } finally {
    await rm(root, { force: true, recursive: true });
  }
});

function createConfig(account?: string): ParadoxConfig {
  return {
    mode: 'write',
    ...(account === undefined ? {} : { donation: { account } }),
    package: { entrypoints: ['src/index.ts'] },
    output: { dir: 'paradox' },
  };
}

async function createFixtureAsync(): Promise<string> {
  const root = join(import.meta.dir, '.tmp', `donation-${Date.now()}-${Math.random()}`);
  await mkdir(join(root, 'src'), { recursive: true });
  await writeFile(
    join(root, 'package.json'),
    JSON.stringify({
      name: '@fixture/donation',
      version: '1.0.0',
      description: 'Donation fixture.',
      license: 'MIT',
    }),
  );
  await writeFile(
    join(root, 'tsconfig.json'),
    JSON.stringify({
      compilerOptions: {
        target: 'ES2022',
        module: 'ESNext',
        moduleResolution: 'Bundler',
        strict: true,
        skipLibCheck: true,
      },
      include: ['src'],
    }),
  );
  await writeFile(join(root, 'src/index.ts'), 'export const value = 1;\n');
  return root;
}

async function renderFixtureAsync(root: string, account?: string) {
  const config = createConfig(account);
  const analysis = await analyze(config, { packageRoot: root });
  const result = render(buildModel(analysis), { outputDir: 'paradox' });
  return { analysis, config, result };
}
