import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

export async function syncCollaboratorsWorkflowAsync(
  packageRoot: string,
  workflowYaml: string | null,
): Promise<void> {
  const workflowPath = join(packageRoot, '.github', 'workflows', 'collaborators.yml');
  const existing = await readCollaboratorsWorkflowAsync(workflowPath);

  if (workflowYaml === null) {
    if (existing !== null && isParadoxOwnedCollaboratorsWorkflow(existing)) {
      await unlink(workflowPath);
    }
    return;
  }

  if (existing !== null && !isParadoxOwnedCollaboratorsWorkflow(existing)) {
    throw new Error(
      'Refusing to overwrite existing non-Paradox .github/workflows/collaborators.yml.',
    );
  }

  await mkdir(dirname(workflowPath), { recursive: true });
  await writeFile(workflowPath, workflowYaml);
}

const generatedWorkflowMarker = '# Generated by Paradox. Do not edit manually.';

function isParadoxOwnedCollaboratorsWorkflow(content: string): boolean {
  return content.startsWith(`${generatedWorkflowMarker}\n`);
}

async function readCollaboratorsWorkflowAsync(path: string): Promise<string | null> {
  try {
    return await readFile(path, 'utf-8');
  } catch (error: unknown) {
    if (error instanceof Error && 'code' in error && error.code === 'ENOENT') return null;
    throw error;
  }
}
