import type { DocumentationModel } from '../../model/types.js';

export function renderFundingYaml(model: DocumentationModel): string | null {
  if (model.donation === null) return null;

  return [
    '# Generated by Paradox. Do not edit manually.',
    `github: ${model.donation.account}`,
    '',
  ].join('\n');
}
