import type { DocumentationModel } from '../../model/types.js';
import type { RenderContext } from '../types.js';

type ConfigMembers = NonNullable<DocumentationModel['config']>['members'];
type ComponentEntry = DocumentationModel['components'][number];
type ExportEntry = DocumentationModel['exports'][number];
type ExampleEntry = ExportEntry['examples'][number];
type ReadmeUsageEntry = DocumentationModel['readmeUsage'][number];
type SequenceScenarioEntry = DocumentationModel['sequenceScenarios'][number];

interface ReadmeGroup {
  title: string;
  items: ReadmeItem[];
}

type ReadmeItem =
  | { kind: 'component'; component: ComponentEntry; exportEntry: ExportEntry | undefined }
  | { kind: 'export'; exportEntry: ExportEntry };

/***
 * Renders markdown artifacts from the documentation model.
 */
export function renderMarkdown({
  badges,
  diagrams,
  model,
  outputDir,
}: RenderContext): Pick<RenderContext['result'], 'components' | 'exportsMarkdown' | 'readme'> {
  return {
    readme: renderReadme(model, outputDir, badges, diagrams),
    exportsMarkdown: renderExports(model),
    components: renderComponents(model),
  };
}

function renderReadme(
  model: DocumentationModel,
  outputDir: string,
  badges: RenderContext['badges'],
  diagrams: RenderContext['diagrams'],
): string {
  const lines = [
    '<!-- markdownlint-disable MD013 MD033 -->',
    '<!-- This file is generated by Paradox. Do not edit manually. -->',
    '',
    `# ${model.packageName}`,
    '',
  ];

  if (badges.length > 0) {
    lines.push(
      badges
        .map((badge) => `![${badgeLabel(model, badge.path)}](./${outputDir}/${badge.path})`)
        .join(' '),
      '',
    );
  }

  if (model.description) {
    lines.push(model.description, '');
  }

  renderReadmeUsage(lines, model.readmeUsage);

  if (model.usage !== null) {
    lines.push('## Installation', '');
    lines.push('```bash');
    for (const command of model.usage.commands) {
      lines.push(command.command);
    }
    lines.push('```', '');
  }

  renderCliScenarios(lines, model, outputDir, diagrams);

  if (model.config?.isReadme) {
    renderConfiguration(lines, model);
  }

  renderGeneratedDocumentation(lines, outputDir, diagrams);
  renderReadmeApi(lines, model);

  return `${lines.join('\n').trimEnd()}\n`;
}

function renderReadmeUsage(lines: string[], entries: readonly ReadmeUsageEntry[]): void {
  if (entries.length === 0) return;

  lines.push('## Usage', '');

  for (const entry of entries) {
    if (entry.title !== null) {
      lines.push(`### ${entry.title}`, '');
    }

    if (entry.description !== null) {
      const [, ...rest] = entry.description.split('\n');
      const body = rest.join('\n').trim();
      if (body.length > 0) lines.push(body, '');
    }

    lines.push(`Source: \`${entry.sourcePath}\``, '');
    lines.push(`\`\`\`${entry.language}`);
    lines.push(entry.code);
    lines.push('```', '');
  }
}

function renderCliScenarios(
  lines: string[],
  model: DocumentationModel,
  outputDir: string,
  diagrams: RenderContext['diagrams'],
): void {
  const scenarios = model.sequenceScenarios.filter(
    (scenario) => scenario.kind === 'bin' && scenario.isReadme,
  );
  if (scenarios.length === 0) return;

  lines.push('## CLI', '');

  for (const scenario of scenarios) {
    lines.push('<details>');
    lines.push(`<summary>${scenario.name}</summary>`, '');

    if (scenario.description !== null) {
      lines.push(scenario.description, '');
    }

    const command = model.usage?.commands.find((item) => item.name === scenario.name);
    if (command !== undefined) {
      lines.push('```bash');
      lines.push(command.command);
      lines.push('```', '');
    }

    const diagram = findScenarioDiagram(diagrams, scenario);
    if (diagram !== undefined) {
      lines.push(`Diagram: [${diagram.title}](./${outputDir}/${diagram.path})`, '');
      lines.push('```mermaid');
      lines.push(diagram.content.trimEnd());
      lines.push('```', '');
    }

    lines.push('</details>', '');
  }
}

function findScenarioDiagram(
  diagrams: RenderContext['diagrams'],
  scenario: SequenceScenarioEntry,
): RenderContext['diagrams'][number] | undefined {
  return diagrams.find(
    (diagram) => diagram.path === `diagrams/sequences/${toFileStem(scenario.name)}.mmd`,
  );
}

function renderConfiguration(lines: string[], model: DocumentationModel): void {
  const { config } = model;
  if (config === null) return;

  lines.push('## Configuration', '');
  lines.push(`Create a \`${config.configFile}\` file:`, '');
  lines.push('```ts');

  if (config.factoryName !== null) {
    lines.push(`import { ${config.factoryName} } from '${model.packageId}';`);
    lines.push('');
    lines.push(`export default ${config.factoryName}({`);
    lines.push('  // ...');
    lines.push('});');
  } else {
    lines.push(`import type { ${config.exportName} } from '${model.packageId}';`);
    lines.push('');
    lines.push('const config = {');
    lines.push('  // ...');
    lines.push(`} satisfies ${config.exportName};`);
    lines.push('');
    lines.push('export default config;');
  }

  lines.push('```', '');

  if (config.members.length > 0) {
    lines.push('<details>');
    lines.push('<summary>Configuration options</summary>', '');
    lines.push('| Field | Type | Required | Default | Description |');
    lines.push('| --- | --- | --- | --- | --- |');

    for (const configMember of flattenConfigMembers(config.members)) {
      lines.push(
        `| ${escapeTableCell(configMember.path)} | \`${escapeTableCell(configMember.type)}\` | ${
          configMember.required ? 'yes' : 'no'
        } | ${renderDefault(configMember.defaultValue)} | ${escapeTableCell(
          configMember.description ?? '',
        )} |`,
      );
    }

    lines.push('', '</details>', '');
  }
}

function renderGeneratedDocumentation(
  lines: string[],
  outputDir: string,
  diagrams: RenderContext['diagrams'],
): void {
  lines.push('## Generated documentation', '');
  lines.push(`- [Interactive documentation app](./${outputDir}/index.html)`);
  lines.push(`- [Public API reference](./${outputDir}/exports.md)`);
  lines.push(`- [Component registry](./${outputDir}/components.md)`);
  for (const diagram of diagrams) {
    lines.push(`- [${diagram.title}](./${outputDir}/${diagram.path})`);
  }
  lines.push('');
}

function renderReadmeApi(lines: string[], model: DocumentationModel): void {
  const groups = getReadmeGroups(model);
  if (groups.length === 0) return;

  lines.push('## Public API', '');
  for (const group of groups) {
    lines.push(`### ${group.title}`, '');
    for (const item of group.items) {
      if (item.kind === 'component') {
        renderComponentAccordion(lines, item.component, item.exportEntry);
      } else {
        renderExportAccordion(lines, item.exportEntry);
      }
    }
  }
}
