import type { DocumentationModel } from '../../model/types.js';
import type { RenderContext } from '../types.js';

type ConfigMembers = NonNullable<DocumentationModel['config']>['members'];
type ComponentEntry = DocumentationModel['components'][number];
type ExportEntry = DocumentationModel['exports'][number];
type ExampleEntry = ExportEntry['examples'][number];
type SequenceScenarioEntry = DocumentationModel['sequenceScenarios'][number];

interface ReadmeGroup {
  title: string;
  items: ReadmeItem[];
}

type ReadmeItem =
  | { kind: 'component'; component: ComponentEntry; exportEntry: ExportEntry | undefined }
  | { kind: 'export'; exportEntry: ExportEntry };

/***
 * Renders markdown artifacts from the documentation model.
 */
export function renderMarkdown({
  badges,
  diagrams,
  model,
  outputDir,
}: RenderContext): Pick<RenderContext['result'], 'components' | 'exportsMarkdown' | 'readme'> {
  return {
    readme: renderReadme(model, outputDir, badges, diagrams),
    exportsMarkdown: renderExports(model),
    components: renderComponents(model),
  };
}

function renderReadme(
  model: DocumentationModel,
  outputDir: string,
  badges: RenderContext['badges'],
  diagrams: RenderContext['diagrams'],
): string {
  const lines = [
    '<!-- markdownlint-disable MD013 MD033 -->',
    '<!-- This file is generated by Paradox. Do not edit manually. -->',
    '',
    `# ${model.packageName}`,
    '',
  ];

  if (badges.length > 0) {
    lines.push(
      badges
        .map((badge) => `![${badgeLabel(model, badge.path)}](./${outputDir}/${badge.path})`)
        .join(' '),
      '',
    );
  }

  if (model.description) {
    lines.push(model.description, '');
  }

  if (model.usage !== null) {
    lines.push('## Installation', '');
    lines.push('```bash');
    for (const command of model.usage.commands) {
      lines.push(command.command);
    }
    lines.push('```', '');
  }

  renderCliScenarios(lines, model, outputDir, diagrams);
  renderDocumentationTags(lines);

  if (model.config?.isReadme) {
    renderConfiguration(lines, model);
  }

  renderGeneratedDocumentation(lines, outputDir, diagrams);
  renderArchitecturePreview(lines, diagrams);
  renderPathResolution(lines);
  renderReadmeApi(lines, model);

  return `${lines.join('\n').trimEnd()}\n`;
}

function renderCliScenarios(
  lines: string[],
  model: DocumentationModel,
  outputDir: string,
  diagrams: RenderContext['diagrams'],
): void {
  const scenarios = model.sequenceScenarios.filter(
    (scenario) => scenario.kind === 'bin' && scenario.isReadme,
  );
  if (scenarios.length === 0) return;

  lines.push('## CLI', '');

  for (const scenario of scenarios) {
    lines.push('<details>');
    lines.push(`<summary>${scenario.name}</summary>`, '');

    if (scenario.description !== null) {
      lines.push(scenario.description, '');
    }

    const command = model.usage?.commands.find((item) => item.name === scenario.name);
    if (command !== undefined) {
      lines.push('```bash');
      lines.push(command.command);
      lines.push('```', '');
    }

    const diagram = findScenarioDiagram(diagrams, scenario);
    if (diagram !== undefined) {
      lines.push(`Diagram: [${diagram.title}](./${outputDir}/${diagram.path})`, '');
      lines.push('```mermaid');
      lines.push(diagram.content.trimEnd());
      lines.push('```', '');
    }

    lines.push('</details>', '');
  }
}

function findScenarioDiagram(
  diagrams: RenderContext['diagrams'],
  scenario: SequenceScenarioEntry,
): RenderContext['diagrams'][number] | undefined {
  return diagrams.find(
    (diagram) => diagram.path === `diagrams/sequences/${toFileStem(scenario.name)}.mmd`,
  );
}

function renderDocumentationTags(lines: string[]): void {
  lines.push('## Documentation Tags', '');
  for (const tag of DOCUMENTATION_TAGS) {
    lines.push('<details>');
    lines.push(`<summary>@${tag.name}</summary>`, '');
    lines.push(tag.description, '');
    lines.push('</details>', '');
  }
}

function renderConfiguration(lines: string[], model: DocumentationModel): void {
  const { config } = model;
  if (config === null) return;

  lines.push('## Configuration', '');
  lines.push(`Create a \`${config.configFile}\` file:`, '');
  lines.push('```ts');

  if (config.factoryName !== null) {
    lines.push(`import { ${config.factoryName} } from '${model.packageId}';`);
    lines.push('');
    lines.push(`export default ${config.factoryName}({`);
    lines.push('  // ...');
    lines.push('});');
  } else {
    lines.push(`import type { ${config.exportName} } from '${model.packageId}';`);
    lines.push('');
    lines.push('const config = {');
    lines.push('  // ...');
    lines.push(`} satisfies ${config.exportName};`);
    lines.push('');
    lines.push('export default config;');
  }

  lines.push('```', '');

  if (config.members.length > 0) {
    lines.push('<details>');
    lines.push('<summary>Configuration options</summary>', '');
    lines.push('| Field | Type | Required | Default | Description |');
    lines.push('| --- | --- | --- | --- | --- |');

    for (const configMember of flattenConfigMembers(config.members)) {
      lines.push(
        `| ${escapeTableCell(configMember.path)} | \`${escapeTableCell(configMember.type)}\` | ${
          configMember.required ? 'yes' : 'no'
        } | ${renderDefault(configMember.defaultValue)} | ${escapeTableCell(
          configMember.description ?? '',
        )} |`,
      );
    }

    lines.push('', '</details>', '');
  }
}

function renderGeneratedDocumentation(
  lines: string[],
  outputDir: string,
  diagrams: RenderContext['diagrams'],
): void {
  lines.push('## Generated documentation', '');
  lines.push(`- [Interactive documentation app](./${outputDir}/index.html)`);
  lines.push(`- [Public API reference](./${outputDir}/exports.md)`);
  lines.push(`- [Component registry](./${outputDir}/components.md)`);
  for (const diagram of diagrams) {
    lines.push(`- [${diagram.title}](./${outputDir}/${diagram.path})`);
  }
  lines.push('');
}

function renderArchitecturePreview(lines: string[], diagrams: RenderContext['diagrams']): void {
  lines.push('## Architecture preview', '');
  if (diagrams.length > 0) {
    lines.push('<details>');
    lines.push('<summary>Architecture overview</summary>', '');
    lines.push('```mermaid');
    lines.push(diagrams[0]?.content.trimEnd() ?? '');
    lines.push('```', '');
    lines.push('</details>', '');
  }
}

function renderPathResolution(lines: string[]): void {
  lines.push('## Path resolution', '');
  lines.push(
    '- Config discovery: searches upward from `process.cwd()` for `paradox.config.ts/js/mjs/cjs` (required; no fallback).',
  );
  lines.push(
    '- Package root: defaults to the directory containing `paradox.config.*`; `package.root` (when relative) resolves relative to that directory.',
  );
  lines.push(
    '- Output directory: defaults to `paradox/`; `output.dir` (when relative) resolves relative to the resolved package root and must stay inside it.',
  );
  lines.push('- Modes:');
  lines.push('  - `safe`: writes generated artifacts only under the output directory');
  lines.push('  - `write`: additionally updates `<packageRoot>/README.md`', '');
}

function renderReadmeApi(lines: string[], model: DocumentationModel): void {
  const groups = getReadmeGroups(model);
  if (groups.length === 0) return;

  lines.push('## Public API', '');
  for (const group of groups) {
    lines.push(`### ${group.title}`, '');
    for (const item of group.items) {
      if (item.kind === 'component') {
        renderComponentAccordion(lines, item.component, item.exportEntry);
      } else {
        renderExportAccordion(lines, item.exportEntry);
      }
    }
  }
}

function renderComponentAccordion(
  lines: string[],
  component: ComponentEntry,
  exportEntry: ExportEntry | undefined,
): void {
  lines.push('<details>');
  lines.push(`<summary>${component.name}</summary>`, '');
  renderSignature(lines, exportEntry);
  if (component.description) lines.push(component.description, '');
  renderExamples(lines, component.examples);
  if (exportEntry && exportEntry.relatedSymbols.length > 0) {
    lines.push(
      `Related types: ${exportEntry.relatedSymbols.map((symbol) => `\`${symbol}\``).join(', ')}`,
      '',
    );
  }
  if (component.props.length > 0) {
    lines.push('<details>');
    lines.push('<summary>Props</summary>', '');
    lines.push('| Prop | Type | Required | Default | Description |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const prop of component.props) {
      lines.push(
        `| ${escapeTableCell(prop.name)} | \`${escapeTableCell(prop.type)}\` | ${
          prop.required ? 'yes' : 'no'
        } | ${renderDefault(prop.defaultValue)} | ${escapeTableCell(prop.description ?? '')} |`,
      );
    }
    lines.push('', '</details>', '');
  }
  lines.push('</details>', '');
}

function renderExportAccordion(lines: string[], item: ExportEntry): void {
  lines.push('<details>');
  lines.push(`<summary>${item.name}</summary>`, '');
  renderSignature(lines, item);
  lines.push(item.description ?? `\`${item.kind}\` export.`, '');
  renderExamples(lines, item.examples);
  lines.push(`Module: \`${item.modulePath}\``);
  lines.push(
    `Source: \`${item.sourceLocation.filePath}:${item.sourceLocation.line}:${item.sourceLocation.column}\``,
  );
  if (item.relatedSymbols.length > 0) {
    lines.push(
      `Related symbols: ${item.relatedSymbols.map((symbol) => `\`${symbol}\``).join(', ')}`,
    );
  }
  lines.push('', '</details>', '');
}

function renderSignature(lines: string[], item: ExportEntry | undefined): void {
  const signature = item?.signatures[0]?.label;
  if (!signature) return;
  lines.push('```ts');
  lines.push(`${item.name}${signature}`);
  lines.push('```', '');
}

function renderExamples(lines: string[], examples: readonly ExampleEntry[]): void {
  for (const example of examples) {
    if (example.title) lines.push(`#### ${example.title}`, '');
    lines.push(`\`\`\`${example.language ?? ''}`);
    lines.push(example.code);
    lines.push('```', '');
  }
}

function getReadmeGroups(model: DocumentationModel): ReadmeGroup[] {
  const exportsByName = new Map(model.exports.map((entry) => [entry.name, entry]));
  const componentNames = new Set(model.components.map((component) => component.name));
  const groups = new Map<string, ReadmeItem[]>();

  for (const component of model.components.filter((entry) => entry.isReadme)) {
    addReadmeItem(groups, getReadmeCategory(component.modulePath, component.name), {
      kind: 'component',
      component,
      exportEntry: exportsByName.get(component.name),
    });
  }

  for (const item of model.exports.filter((entry) => entry.isReadme)) {
    if (componentNames.has(item.name)) continue;
    addReadmeItem(groups, getReadmeCategory(item.modulePath, item.name), {
      kind: 'export',
      exportEntry: item,
    });
  }

  return CATEGORY_ORDER.flatMap((title) => {
    const items = groups.get(title);
    if (!items || items.length === 0) return [];
    return [{ title, items: sortReadmeItems(items) }];
  });
}

function addReadmeItem(groups: Map<string, ReadmeItem[]>, title: string, item: ReadmeItem): void {
  const existing = groups.get(title) ?? [];
  existing.push(item);
  groups.set(title, existing);
}

function sortReadmeItems(items: readonly ReadmeItem[]): ReadmeItem[] {
  return [...items].sort((left, right) =>
    getReadmeItemName(left).localeCompare(getReadmeItemName(right)),
  );
}

function getReadmeItemName(item: ReadmeItem): string {
  return item.kind === 'component' ? item.component.name : item.exportEntry.name;
}

function getReadmeCategory(modulePath: string, name: string): string {
  if (modulePath.includes('/config/')) return 'Configuration';
  if (modulePath.includes('/primitives/')) return 'Primitives';
  if (modulePath.includes('/components/')) return 'Components';
  if (modulePath.includes('/patterns/')) return 'Patterns';
  if (modulePath.includes('/layout/')) return 'Layout';
  if (modulePath.includes('/hooks/') || /^use[A-Z]/.test(name)) return 'Hooks';
  if (modulePath.includes('/utils/')) return 'Utilities';
  if (modulePath.endsWith('types.ts') || modulePath.includes('/types/')) return 'Types';
  return 'Utilities';
}

function renderExports(model: DocumentationModel): string {
  const lines = ['# Public API', ''];

  for (const item of model.exports) {
    lines.push(`## ${item.name}`, '');
    lines.push(`Kind: \`${item.kind}\``);
    lines.push(`Module: \`${item.modulePath}\``);
    lines.push(
      `Source: \`${item.sourceLocation.filePath}:${item.sourceLocation.line}:${item.sourceLocation.column}\``,
      '',
    );

    if (item.description) {
      lines.push(item.description, '');
    }

    if (item.signatures.length > 0) {
      lines.push('### Signatures', '');
      for (const signature of item.signatures) {
        lines.push(`- \`${signature.label}\``);
        for (const parameter of signature.parameters) {
          lines.push(
            `  - ${parameter.name}: \`${parameter.type}\`${parameter.required ? '' : ' (optional)'}${
              parameter.description ? ` — ${parameter.description}` : ''
            }`,
          );
        }
        lines.push(
          `  - returns: \`${signature.returnType ?? 'void'}\`${
            signature.returnDescription ? ` — ${signature.returnDescription}` : ''
          }`,
        );
      }
      lines.push('');
    }

    if (item.members.length > 0) {
      lines.push('### Members', '');
      lines.push('| Name | Kind | Type | Required | Description |');
      lines.push('| --- | --- | --- | --- | --- |');
      for (const member of item.members) {
        lines.push(
          `| ${escapeTableCell(member.name)} | ${member.kind} | \`${escapeTableCell(
            member.type,
          )}\` | ${member.required ? 'yes' : 'no'} | ${escapeTableCell(member.description ?? '')} |`,
        );
      }
      lines.push('');
    }
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function renderComponents(model: DocumentationModel): string {
  const lines = ['# Components', ''];

  for (const component of model.components) {
    lines.push(`## ${component.name}`, '');
    lines.push(
      `Source: \`${component.sourceLocation.filePath}:${component.sourceLocation.line}:${component.sourceLocation.column}\``,
      '',
    );

    if (component.description) {
      lines.push(component.description, '');
    }

    if (component.exportPaths.length > 0) {
      lines.push(
        `Export paths: ${component.exportPaths.map((path) => `\`${path}\``).join(', ')}`,
        '',
      );
    }

    if (component.props.length > 0) {
      lines.push('| Prop | Type | Required | Default | Description |');
      lines.push('| --- | --- | --- | --- | --- |');

      for (const prop of component.props) {
        lines.push(
          `| ${escapeTableCell(prop.name)} | \`${escapeTableCell(prop.type)}\` | ${
            prop.required ? 'yes' : 'no'
          } | ${renderDefault(prop.defaultValue)} | ${escapeTableCell(prop.description ?? '')} |`,
        );
      }

      lines.push('');
    }
  }

  return `${lines.join('\n').trimEnd()}\n`;
}

function escapeTableCell(value: string): string {
  return value.replaceAll('|', '\\|');
}

function renderDefault(value: string | undefined): string {
  return value === undefined ? '—' : `\`${escapeTableCell(value)}\``;
}

function flattenConfigMembers(
  members: ConfigMembers,
  prefix = '',
): {
  path: string;
  type: string;
  required: boolean;
  description: string | null;
  defaultValue?: string;
}[] {
  return members.flatMap((member) => {
    const path = prefix ? `${prefix}.${member.name}` : member.name;
    const current = {
      path,
      type: member.type,
      required: member.required,
      description: member.description,
      defaultValue: member.defaultValue,
    };
    const children = member.children ? flattenConfigMembers(member.children, path) : [];
    return [current, ...children];
  });
}

function badgeLabel(model: DocumentationModel, badgePath: string): string {
  const fileName = badgePath.split('/').pop();
  if (!fileName) {
    return badgePath;
  }

  const id = fileName.replace(/\.svg$/, '');
  const badge = model.badges.find((entry) => entry.id === id);

  return badge ? `${badge.label}: ${badge.value}` : badgePath;
}

function toFileStem(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/[^A-Za-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
}

const CATEGORY_ORDER = [
  'Configuration',
  'Primitives',
  'Components',
  'Patterns',
  'Layout',
  'Hooks',
  'Utilities',
  'Types',
];

const DOCUMENTATION_TAGS = [
  {
    name: 'readme',
    description: 'Includes a documentation block or exported symbol in README output.',
  },
  {
    name: 'config',
    description:
      'Marks a type or interface as part of the Paradox configuration model. `@config` alone does not imply README inclusion; use `@config` plus `@readme` for README output.',
  },
  {
    name: 'example',
    description: 'Adds a titled fenced code example to the generated documentation for a symbol.',
  },
];
