sequenceDiagram
participant participant_main as main
participant participant_findParadoxConfigFile as findParadoxConfigFile
participant participant_dirname as dirname
participant participant_loadParadoxConfig as loadParadoxConfig
participant participant_resolvePackageRoot as resolvePackageRoot
participant participant_resolveOutputRoot as resolveOutputRoot
participant participant_analyze as analyze
participant participant_buildModel as buildModel
participant participant_render as render
participant participant_write as write
participant participant_src_cli_ts as src/cli.ts
participant participant_readPackageJson as readPackageJson
participant participant_createUsageFromPackageJson as createUsageFromPackageJson
participant participant_analyzeBadges as analyzeBadges
participant participant_createProject as createProject
participant participant_createTypeScriptProgram as createTypeScriptProgram
participant participant_analyzeExports as analyzeExports
participant participant_analyzeComponents as analyzeComponents
participant participant_analyzeModules as analyzeModules
participant participant_collectTypeMembers as collectTypeMembers
participant participant_resolveTypeReference as resolveTypeReference
participant participant_collectImportGraph as collectImportGraph
participant participant_collectCallGraph as collectCallGraph
participant participant_collectComponentCompositionGraph as collectComponentCompositionGraph
participant participant_mapTypeMembers as mapTypeMembers
participant participant_src_analyze_analyze_ts as src/analyze/analyze.ts
participant participant_readFile as readFile
participant participant_join as join
participant participant_readWorkflowFiles as readWorkflowFiles
participant participant_hasAnyFile as hasAnyFile
participant participant_scriptContains as scriptContains
participant participant_workflowRunsScript as workflowRunsScript
participant participant_hasScript as hasScript
participant participant_hasTypeScriptStrictMode as hasTypeScriptStrictMode
participant participant_supportsBun as supportsBun
participant participant_readCoveragePercent as readCoveragePercent
participant participant_formatPercent as formatPercent
participant participant_getCoverageColor as getCoverageColor
participant participant_sortBadges as sortBadges
participant participant_fileExists as fileExists
participant participant_readJsonFile as readJsonFile
participant participant_escapeRegExp as escapeRegExp
participant participant_readDirectory as readDirectory
participant participant_src_analyze_badges_ts as src/analyze/badges.ts
participant participant_readdir as readdir
participant participant_isNotFoundError as isNotFoundError
participant participant_access as access
participant participant_getBadgeOrder as getBadgeOrder
participant participant_isReactComponent as isReactComponent
participant participant_collectPropsForExport as collectPropsForExport
participant participant_getComponentPropsType as getComponentPropsType
participant participant_getPropsFromType as getPropsFromType
participant participant_getEntryPointSourceFiles as getEntryPointSourceFiles
participant participant_toPosixPath as toPosixPath
participant participant_relative as relative
participant participant_resolveExportSymbol as resolveExportSymbol
participant participant_getFirstDeclaration as getFirstDeclaration
participant participant_getParadoxComment as getParadoxComment
participant participant_parseParadoxComment as parseParadoxComment
participant participant_createEmptyMetadata as createEmptyMetadata
participant participant_getExportMetadata as getExportMetadata
participant participant_uniqueSorted as uniqueSorted
participant participant_inferKind as inferKind
participant participant_src_analyze_exports_ts as src/analyze/exports.ts
participant participant_normalize as normalize
participant participant_isAbsolute as isAbsolute
participant participant_src_analyze_modules_ts as src/analyze/modules.ts
participant participant_getPackageBaseName as getPackageBaseName
participant participant_src_model_buildModel_ts as src/model/buildModel.ts
participant participant_mapExport as mapExport
participant participant_sortByName as sortByName
participant participant_getDefaultConfigFileName as getDefaultConfigFileName
participant participant_findConfigFactoryName as findConfigFactoryName
participant participant_mapComponent as mapComponent
participant participant_resolve as resolve
participant participant_pathExists as pathExists
participant participant_pathToFileURL as pathToFileURL
participant participant_assertPathExists as assertPathExists
participant participant_validateOutputDir as validateOutputDir
participant participant_assertWithinRoot as assertWithinRoot
participant participant_splitPathSegments as splitPathSegments
participant participant_renderBadgeArtifacts as renderBadgeArtifacts
participant participant_renderDiagramArtifacts as renderDiagramArtifacts
participant participant_renderer as renderer
participant participant_mkdir as mkdir
participant participant_writeFile as writeFile
participant participant_analyzeProject as analyzeProject
participant participant_collectSourceFiles as collectSourceFiles
participant participant_src_analyze_semantic_analyzeProject_ts as src/analyze/semantic/analyzeProject.ts
participant participant_collectDocBlocks as collectDocBlocks
participant participant_associateDocBlocksWithSymbols as associateDocBlocksWithSymbols
participant participant_collectExports as collectExports
participant participant_getExportSignature as getExportSignature
participant participant_collectRelatedTypes as collectRelatedTypes
participant participant_src_analyze_semantic_associateDocBlocksWithSymbols_ts as src/analyze/semantic/associateDocBlocksWithSymbols.ts
participant participant_relativeToRoot as relativeToRoot
participant participant_src_analyze_semantic_collectSourceFiles_ts as src/analyze/semantic/collectSourceFiles.ts
participant participant_isPathInsideRoot as isPathInsideRoot
participant participant_isNodeModulePath as isNodeModulePath
participant participant_src_analyze_semantic_createTypeScriptProgram_ts as src/analyze/semantic/createTypeScriptProgram.ts
participant participant_parseDocBlock as parseDocBlock
participant participant_collectTags as collectTags
participant participant_normalizeDocBlock as normalizeDocBlock
participant participant_detectExportKind as detectExportKind
participant participant_getDeclarationName as getDeclarationName
participant participant_getCallableNode as getCallableNode
participant participant_src_analyze_semantic_exports_ts as src/analyze/semantic/exports.ts
participant participant_getParameterTypeText as getParameterTypeText
participant participant_collectMembersFromType as collectMembersFromType
participant participant_collectDefaultValuesFromBinding as collectDefaultValuesFromBinding
participant participant_flattenMembers as flattenMembers
participant participant_getDeclaredMembers as getDeclaredMembers
participant participant_isUndefinedUnion as isUndefinedUnion
participant participant_shouldExpandType as shouldExpandType
participant participant_getDeclaredTypeText as getDeclaredTypeText
participant participant_appendUndefinedIfOptional as appendUndefinedIfOptional
participant participant_uniqueEdges as uniqueEdges
participant participant_src_analyze_semantic_graphs_ts as src/analyze/semantic/graphs.ts
participant participant_toCallEdge as toCallEdge
participant participant_findJsxElements as findJsxElements
participant participant_getEnclosingSymbolName as getEnclosingSymbolName
participant participant_key as key
participant participant_getCallSignature as getCallSignature
participant participant_getSourceLocation as getSourceLocation
participant participant_getSignatures as getSignatures
participant participant_getMembers as getMembers
participant participant_collectRelatedSymbols as collectRelatedSymbols
participant participant_readParadoxMetadata as readParadoxMetadata
participant participant_getCallableDeclarations as getCallableDeclarations
participant participant_src_analyze_utils_getExportMetadata_ts as src/analyze/utils/getExportMetadata.ts
participant participant_getSignature as getSignature
participant participant_uniqueBy as uniqueBy
participant participant_getMembersFromProperties as getMembersFromProperties
participant participant_isMemberMethodDeclaration as isMemberMethodDeclaration
participant participant_src_analyze_utils_getPropsFromType_ts as src/analyze/utils/getPropsFromType.ts
participant participant_normalizeCommentLines as normalizeCommentLines
participant participant_parseExample as parseExample
participant participant_src_render_renderers_badges_ts as src/render/renderers/badges.ts
participant participant_renderBadgeSvg as renderBadgeSvg
participant participant_getTextWidth as getTextWidth
participant participant_escapeXml as escapeXml
participant participant_renderArchitectureOverview as renderArchitectureOverview
participant participant_renderModuleRelationships as renderModuleRelationships
participant participant_renderExportGraph as renderExportGraph
participant participant_renderEntrypointSequence as renderEntrypointSequence
participant participant_toMermaidId as toMermaidId
participant participant_escapeLabel as escapeLabel
participant participant_src_render_renderers_diagrams_ts as src/render/renderers/diagrams.ts
participant participant_renderFallbackEdge as renderFallbackEdge
participant participant_src_render_renderers_html_ts as src/render/renderers/html.ts
participant participant_toAnchorId as toAnchorId
participant participant_renderHtml as renderHtml
participant participant_groupBy as groupBy
participant participant_escapeHtml as escapeHtml
participant participant_escapeAttribute as escapeAttribute
participant participant_renderExportCard as renderExportCard
participant participant_renderModuleCard as renderModuleCard
participant participant_renderInlineCodeList as renderInlineCodeList
participant participant_renderChipList as renderChipList
participant participant_renderSignatureBlock as renderSignatureBlock
participant participant_renderMemberTable as renderMemberTable
participant participant_renderComponentCard as renderComponentCard
participant participant_renderDiagramCard as renderDiagramCard
participant participant_renderMarkdown as renderMarkdown
participant participant_renderReadme as renderReadme
participant participant_renderExports as renderExports
participant participant_renderComponents as renderComponents
participant participant_src_render_renderers_markdown_ts as src/render/renderers/markdown.ts
participant participant_badgeLabel as badgeLabel
participant participant_renderDocumentationTags as renderDocumentationTags
participant participant_renderConfiguration as renderConfiguration
participant participant_renderGeneratedDocumentation as renderGeneratedDocumentation
participant participant_renderArchitecturePreview as renderArchitecturePreview
participant participant_renderPathResolution as renderPathResolution
participant participant_renderReadmeApi as renderReadmeApi
participant participant_flattenConfigMembers as flattenConfigMembers
participant participant_escapeTableCell as escapeTableCell
participant participant_renderDefault as renderDefault
participant participant_getReadmeGroups as getReadmeGroups
participant participant_renderComponentAccordion as renderComponentAccordion
participant participant_renderExportAccordion as renderExportAccordion
participant participant_renderSignature as renderSignature
participant participant_renderExamples as renderExamples
participant participant_addReadmeItem as addReadmeItem
participant participant_getReadmeCategory as getReadmeCategory
participant participant_sortReadmeItems as sortReadmeItems
participant participant_getReadmeItemName as getReadmeItemName
  participant_main->>participant_findParadoxConfigFile: findParadoxConfigFile
  participant_main->>participant_dirname: dirname
  participant_main->>participant_loadParadoxConfig: loadParadoxConfig
  participant_main->>participant_resolvePackageRoot: resolvePackageRoot
  participant_main->>participant_resolveOutputRoot: resolveOutputRoot
  participant_main->>participant_analyze: analyze
  participant_main->>participant_buildModel: buildModel
  participant_main->>participant_render: render
  participant_main->>participant_write: write
  participant_src_cli_ts->>participant_main: main
  participant_analyze->>participant_readPackageJson: readPackageJson
  participant_analyze->>participant_createUsageFromPackageJson: createUsageFromPackageJson
  participant_analyze->>participant_analyzeBadges: analyzeBadges
  participant_analyze->>participant_createProject: createProject
  participant_analyze->>participant_createTypeScriptProgram: createTypeScriptProgram
  participant_analyze->>participant_analyzeExports: analyzeExports
  participant_analyze->>participant_analyzeComponents: analyzeComponents
  participant_analyze->>participant_analyzeModules: analyzeModules
  participant_analyze->>participant_collectTypeMembers: collectTypeMembers
  participant_analyze->>participant_resolveTypeReference: resolveTypeReference
  participant_analyze->>participant_collectImportGraph: collectImportGraph
  participant_analyze->>participant_collectCallGraph: collectCallGraph
  participant_analyze->>participant_collectComponentCompositionGraph: collectComponentCompositionGraph
  participant_analyze->>participant_mapTypeMembers: mapTypeMembers
  participant_src_analyze_analyze_ts->>participant_mapTypeMembers: mapTypeMembers
  participant_readPackageJson->>participant_readFile: readFile
  participant_readPackageJson->>participant_join: join
  participant_analyzeBadges->>participant_readWorkflowFiles: readWorkflowFiles
  participant_analyzeBadges->>participant_hasAnyFile: hasAnyFile
  participant_analyzeBadges->>participant_scriptContains: scriptContains
  participant_analyzeBadges->>participant_workflowRunsScript: workflowRunsScript
  participant_analyzeBadges->>participant_hasScript: hasScript
  participant_analyzeBadges->>participant_hasTypeScriptStrictMode: hasTypeScriptStrictMode
  participant_analyzeBadges->>participant_supportsBun: supportsBun
  participant_analyzeBadges->>participant_readCoveragePercent: readCoveragePercent
  participant_analyzeBadges->>participant_formatPercent: formatPercent
  participant_analyzeBadges->>participant_getCoverageColor: getCoverageColor
  participant_analyzeBadges->>participant_sortBadges: sortBadges
  participant_hasAnyFile->>participant_fileExists: fileExists
  participant_hasAnyFile->>participant_join: join
  participant_hasTypeScriptStrictMode->>participant_readJsonFile: readJsonFile
  participant_hasTypeScriptStrictMode->>participant_join: join
  participant_readCoveragePercent->>participant_readJsonFile: readJsonFile
  participant_readCoveragePercent->>participant_join: join
  participant_workflowRunsScript->>participant_escapeRegExp: escapeRegExp
  participant_readWorkflowFiles->>participant_join: join
  participant_readWorkflowFiles->>participant_readDirectory: readDirectory
  participant_src_analyze_badges_ts->>participant_readFile: readFile
  participant_src_analyze_badges_ts->>participant_join: join
  participant_readDirectory->>participant_readdir: readdir
  participant_readDirectory->>participant_isNotFoundError: isNotFoundError
  participant_readJsonFile->>participant_readFile: readFile
  participant_readJsonFile->>participant_isNotFoundError: isNotFoundError
  participant_fileExists->>participant_access: access
  participant_fileExists->>participant_isNotFoundError: isNotFoundError
  participant_src_analyze_badges_ts->>participant_getBadgeOrder: getBadgeOrder
  participant_analyzeComponents->>participant_isReactComponent: isReactComponent
  participant_analyzeComponents->>participant_collectPropsForExport: collectPropsForExport
  participant_analyzeComponents->>participant_getComponentPropsType: getComponentPropsType
  participant_analyzeComponents->>participant_getPropsFromType: getPropsFromType
  participant_analyzeExports->>participant_getEntryPointSourceFiles: getEntryPointSourceFiles
  participant_analyzeExports->>participant_toPosixPath: toPosixPath
  participant_analyzeExports->>participant_relative: relative
  participant_analyzeExports->>participant_resolveExportSymbol: resolveExportSymbol
  participant_analyzeExports->>participant_getFirstDeclaration: getFirstDeclaration
  participant_analyzeExports->>participant_getParadoxComment: getParadoxComment
  participant_analyzeExports->>participant_parseParadoxComment: parseParadoxComment
  participant_analyzeExports->>participant_createEmptyMetadata: createEmptyMetadata
  participant_analyzeExports->>participant_getExportMetadata: getExportMetadata
  participant_analyzeExports->>participant_uniqueSorted: uniqueSorted
  participant_analyzeExports->>participant_inferKind: inferKind
  participant_src_analyze_exports_ts->>participant_normalize: normalize
  participant_src_analyze_exports_ts->>participant_isAbsolute: isAbsolute
  participant_src_analyze_exports_ts->>participant_join: join
  participant_analyzeModules->>participant_normalize: normalize
  participant_src_analyze_modules_ts->>participant_normalize: normalize
  participant_src_analyze_modules_ts->>participant_isAbsolute: isAbsolute
  participant_src_analyze_modules_ts->>participant_join: join
  participant_src_analyze_modules_ts->>participant_toPosixPath: toPosixPath
  participant_src_analyze_modules_ts->>participant_relative: relative
  participant_src_analyze_modules_ts->>participant_uniqueSorted: uniqueSorted
  participant_createUsageFromPackageJson->>participant_getPackageBaseName: getPackageBaseName
  participant_src_model_buildModel_ts->>participant_mapExport: mapExport
  participant_buildModel->>participant_sortByName: sortByName
  participant_buildModel->>participant_getDefaultConfigFileName: getDefaultConfigFileName
  participant_buildModel->>participant_findConfigFactoryName: findConfigFactoryName
  participant_src_model_buildModel_ts->>participant_mapComponent: mapComponent
  participant_src_model_buildModel_ts->>participant_sortByName: sortByName
  participant_mapExport->>participant_sortByName: sortByName
  participant_mapComponent->>participant_sortByName: sortByName
  participant_findParadoxConfigFile->>participant_resolve: resolve
  participant_findParadoxConfigFile->>participant_dirname: dirname
  participant_findParadoxConfigFile->>participant_join: join
  participant_findParadoxConfigFile->>participant_pathExists: pathExists
  participant_loadParadoxConfig->>participant_pathToFileURL: pathToFileURL
  participant_resolvePackageRoot->>participant_isAbsolute: isAbsolute
  participant_resolvePackageRoot->>participant_resolve: resolve
  participant_resolvePackageRoot->>participant_assertPathExists: assertPathExists
  participant_resolvePackageRoot->>participant_join: join
  participant_resolveOutputRoot->>participant_validateOutputDir: validateOutputDir
  participant_resolveOutputRoot->>participant_resolve: resolve
  participant_resolveOutputRoot->>participant_assertWithinRoot: assertWithinRoot
  participant_pathExists->>participant_access: access
  participant_assertPathExists->>participant_pathExists: pathExists
  participant_validateOutputDir->>participant_normalize: normalize
  participant_validateOutputDir->>participant_isAbsolute: isAbsolute
  participant_validateOutputDir->>participant_splitPathSegments: splitPathSegments
  participant_assertWithinRoot->>participant_relative: relative
  participant_render->>participant_renderBadgeArtifacts: renderBadgeArtifacts
  participant_render->>participant_renderDiagramArtifacts: renderDiagramArtifacts
  participant_render->>participant_renderer: renderer
  participant_write->>participant_mkdir: mkdir
  participant_write->>participant_writeFile: writeFile
  participant_write->>participant_join: join
  participant_write->>participant_dirname: dirname
  participant_analyzeProject->>participant_createTypeScriptProgram: createTypeScriptProgram
  participant_analyzeProject->>participant_collectSourceFiles: collectSourceFiles
  participant_src_analyze_semantic_analyzeProject_ts->>participant_collectDocBlocks: collectDocBlocks
  participant_analyzeProject->>participant_associateDocBlocksWithSymbols: associateDocBlocksWithSymbols
  participant_analyzeProject->>participant_collectExports: collectExports
  participant_src_analyze_semantic_analyzeProject_ts->>participant_getExportSignature: getExportSignature
  participant_src_analyze_semantic_analyzeProject_ts->>participant_collectPropsForExport: collectPropsForExport
  participant_src_analyze_semantic_analyzeProject_ts->>participant_resolveTypeReference: resolveTypeReference
  participant_src_analyze_semantic_analyzeProject_ts->>participant_collectTypeMembers: collectTypeMembers
  participant_src_analyze_semantic_analyzeProject_ts->>participant_collectRelatedTypes: collectRelatedTypes
  participant_analyzeProject->>participant_collectImportGraph: collectImportGraph
  participant_analyzeProject->>participant_collectCallGraph: collectCallGraph
  participant_analyzeProject->>participant_collectComponentCompositionGraph: collectComponentCompositionGraph
  participant_src_analyze_semantic_associateDocBlocksWithSymbols_ts->>participant_relativeToRoot: relativeToRoot
  participant_src_analyze_semantic_collectSourceFiles_ts->>participant_normalize: normalize
  participant_src_analyze_semantic_collectSourceFiles_ts->>participant_isPathInsideRoot: isPathInsideRoot
  participant_src_analyze_semantic_collectSourceFiles_ts->>participant_isNodeModulePath: isNodeModulePath
  participant_src_analyze_semantic_collectSourceFiles_ts->>participant_relativeToRoot: relativeToRoot
  participant_createTypeScriptProgram->>participant_normalize: normalize
  participant_src_analyze_semantic_createTypeScriptProgram_ts->>participant_normalize: normalize
  participant_src_analyze_semantic_createTypeScriptProgram_ts->>participant_isAbsolute: isAbsolute
  participant_src_analyze_semantic_createTypeScriptProgram_ts->>participant_join: join
  participant_createTypeScriptProgram->>participant_join: join
  participant_src_analyze_semantic_createTypeScriptProgram_ts->>participant_toPosixPath: toPosixPath
  participant_collectDocBlocks->>participant_relativeToRoot: relativeToRoot
  participant_collectDocBlocks->>participant_parseDocBlock: parseDocBlock
  participant_collectTags->>participant_normalizeDocBlock: normalizeDocBlock
  participant_parseDocBlock->>participant_normalizeDocBlock: normalizeDocBlock
  participant_parseDocBlock->>participant_collectTags: collectTags
  participant_collectExports->>participant_relativeToRoot: relativeToRoot
  participant_collectExports->>participant_resolveExportSymbol: resolveExportSymbol
  participant_collectExports->>participant_getFirstDeclaration: getFirstDeclaration
  participant_collectExports->>participant_uniqueSorted: uniqueSorted
  participant_collectExports->>participant_detectExportKind: detectExportKind
  participant_detectExportKind->>participant_isReactComponent: isReactComponent
  participant_detectExportKind->>participant_getDeclarationName: getDeclarationName
  participant_getExportSignature->>participant_getCallableNode: getCallableNode
  participant_src_analyze_semantic_exports_ts->>participant_getFirstDeclaration: getFirstDeclaration
  participant_src_analyze_semantic_exports_ts->>participant_getParameterTypeText: getParameterTypeText
  participant_resolveTypeReference->>participant_getFirstDeclaration: getFirstDeclaration
  participant_resolveTypeReference->>participant_relativeToRoot: relativeToRoot
  participant_collectTypeMembers->>participant_collectMembersFromType: collectMembersFromType
  participant_collectTypeMembers->>participant_resolveTypeReference: resolveTypeReference
  participant_collectTypeMembers->>participant_collectTypeMembers: collectTypeMembers
  participant_collectPropsForExport->>participant_getCallableNode: getCallableNode
  participant_collectPropsForExport->>participant_resolveTypeReference: resolveTypeReference
  participant_collectPropsForExport->>participant_collectDefaultValuesFromBinding: collectDefaultValuesFromBinding
  participant_collectPropsForExport->>participant_collectTypeMembers: collectTypeMembers
  participant_collectRelatedTypes->>participant_flattenMembers: flattenMembers
  participant_collectMembersFromType->>participant_getDeclaredMembers: getDeclaredMembers
  participant_src_analyze_semantic_exports_ts->>participant_getParadoxComment: getParadoxComment
  participant_src_analyze_semantic_exports_ts->>participant_parseParadoxComment: parseParadoxComment
  participant_src_analyze_semantic_exports_ts->>participant_isUndefinedUnion: isUndefinedUnion
  participant_src_analyze_semantic_exports_ts->>participant_shouldExpandType: shouldExpandType
  participant_src_analyze_semantic_exports_ts->>participant_resolveTypeReference: resolveTypeReference
  participant_src_analyze_semantic_exports_ts->>participant_collectTypeMembers: collectTypeMembers
  participant_src_analyze_semantic_exports_ts->>participant_getDeclaredTypeText: getDeclaredTypeText
  participant_src_analyze_semantic_exports_ts->>participant_appendUndefinedIfOptional: appendUndefinedIfOptional
  participant_shouldExpandType->>participant_getFirstDeclaration: getFirstDeclaration
  participant_shouldExpandType->>participant_relativeToRoot: relativeToRoot
  participant_src_analyze_semantic_exports_ts->>participant_isPathInsideRoot: isPathInsideRoot
  participant_src_analyze_semantic_exports_ts->>participant_isNodeModulePath: isNodeModulePath
  participant_src_analyze_semantic_exports_ts->>participant_flattenMembers: flattenMembers
  participant_collectImportGraph->>participant_isPathInsideRoot: isPathInsideRoot
  participant_collectImportGraph->>participant_isNodeModulePath: isNodeModulePath
  participant_collectImportGraph->>participant_relativeToRoot: relativeToRoot
  participant_collectImportGraph->>participant_uniqueEdges: uniqueEdges
  participant_collectCallGraph->>participant_isPathInsideRoot: isPathInsideRoot
  participant_collectCallGraph->>participant_isNodeModulePath: isNodeModulePath
  participant_collectCallGraph->>participant_relativeToRoot: relativeToRoot
  participant_src_analyze_semantic_graphs_ts->>participant_toCallEdge: toCallEdge
  participant_collectCallGraph->>participant_uniqueEdges: uniqueEdges
  participant_collectComponentCompositionGraph->>participant_collectExports: collectExports
  participant_collectComponentCompositionGraph->>participant_findJsxElements: findJsxElements
  participant_collectComponentCompositionGraph->>participant_uniqueEdges: uniqueEdges
  participant_toCallEdge->>participant_isPathInsideRoot: isPathInsideRoot
  participant_toCallEdge->>participant_isNodeModulePath: isNodeModulePath
  participant_toCallEdge->>participant_getEnclosingSymbolName: getEnclosingSymbolName
  participant_src_analyze_semantic_graphs_ts->>participant_key: key
  participant_isReactComponent->>participant_getDeclarationName: getDeclarationName
  participant_isReactComponent->>participant_getCallSignature: getCallSignature
  participant_relativeToRoot->>participant_toPosixPath: toPosixPath
  participant_relativeToRoot->>participant_relative: relative
  participant_isPathInsideRoot->>participant_normalize: normalize
  participant_isNodeModulePath->>participant_toPosixPath: toPosixPath
  participant_getComponentPropsType->>participant_getCallSignature: getCallSignature
  participant_getExportMetadata->>participant_toPosixPath: toPosixPath
  participant_getExportMetadata->>participant_relative: relative
  participant_getExportMetadata->>participant_getSourceLocation: getSourceLocation
  participant_getExportMetadata->>participant_getSignatures: getSignatures
  participant_getExportMetadata->>participant_getMembers: getMembers
  participant_getExportMetadata->>participant_collectRelatedSymbols: collectRelatedSymbols
  participant_getSourceLocation->>participant_toPosixPath: toPosixPath
  participant_getSourceLocation->>participant_relative: relative
  participant_getSignatures->>participant_readParadoxMetadata: readParadoxMetadata
  participant_getSignatures->>participant_getCallableDeclarations: getCallableDeclarations
  participant_src_analyze_utils_getExportMetadata_ts->>participant_getSignature: getSignature
  participant_getSignatures->>participant_uniqueBy: uniqueBy
  participant_getMembers->>participant_getCallableNode: getCallableNode
  participant_getMembers->>participant_getMembersFromProperties: getMembersFromProperties
  participant_src_analyze_utils_getExportMetadata_ts->>participant_getFirstDeclaration: getFirstDeclaration
  participant_src_analyze_utils_getExportMetadata_ts->>participant_getParadoxComment: getParadoxComment
  participant_src_analyze_utils_getExportMetadata_ts->>participant_parseParadoxComment: parseParadoxComment
  participant_src_analyze_utils_getExportMetadata_ts->>participant_isMemberMethodDeclaration: isMemberMethodDeclaration
  participant_src_analyze_utils_getExportMetadata_ts->>participant_getCallableNode: getCallableNode
  participant_getCallableDeclarations->>participant_getCallableNode: getCallableNode
  participant_readParadoxMetadata->>participant_getParadoxComment: getParadoxComment
  participant_readParadoxMetadata->>participant_parseParadoxComment: parseParadoxComment
  participant_src_analyze_utils_getExportMetadata_ts->>participant_key: key
  participant_src_analyze_utils_getPropsFromType_ts->>participant_getParadoxComment: getParadoxComment
  participant_src_analyze_utils_getPropsFromType_ts->>participant_parseParadoxComment: parseParadoxComment
  participant_isReactComponent->>participant_getDeclarationName: getDeclarationName
  participant_isReactComponent->>participant_getCallSignature: getCallSignature
  participant_parseParadoxComment->>participant_normalizeCommentLines: normalizeCommentLines
  participant_parseParadoxComment->>participant_parseExample: parseExample
  participant_src_render_renderers_badges_ts->>participant_renderBadgeSvg: renderBadgeSvg
  participant_renderBadgeSvg->>participant_getTextWidth: getTextWidth
  participant_renderBadgeSvg->>participant_escapeXml: escapeXml
  participant_renderDiagramArtifacts->>participant_renderArchitectureOverview: renderArchitectureOverview
  participant_renderDiagramArtifacts->>participant_renderModuleRelationships: renderModuleRelationships
  participant_renderDiagramArtifacts->>participant_renderExportGraph: renderExportGraph
  participant_renderDiagramArtifacts->>participant_renderEntrypointSequence: renderEntrypointSequence
  participant_renderArchitectureOverview->>participant_toMermaidId: toMermaidId
  participant_renderArchitectureOverview->>participant_escapeLabel: escapeLabel
  participant_renderModuleRelationships->>participant_toMermaidId: toMermaidId
  participant_renderModuleRelationships->>participant_escapeLabel: escapeLabel
  participant_src_render_renderers_diagrams_ts->>participant_toMermaidId: toMermaidId
  participant_renderModuleRelationships->>participant_renderFallbackEdge: renderFallbackEdge
  participant_renderExportGraph->>participant_toMermaidId: toMermaidId
  participant_renderExportGraph->>participant_escapeLabel: escapeLabel
  participant_renderEntrypointSequence->>participant_toMermaidId: toMermaidId
  participant_src_render_renderers_html_ts->>participant_toAnchorId: toAnchorId
  participant_renderHtml->>participant_groupBy: groupBy
  participant_renderHtml->>participant_escapeHtml: escapeHtml
  participant_src_render_renderers_html_ts->>participant_escapeAttribute: escapeAttribute
  participant_src_render_renderers_html_ts->>participant_escapeHtml: escapeHtml
  participant_src_render_renderers_html_ts->>participant_renderExportCard: renderExportCard
  participant_renderModuleCard->>participant_escapeAttribute: escapeAttribute
  participant_renderModuleCard->>participant_escapeHtml: escapeHtml
  participant_renderModuleCard->>participant_renderInlineCodeList: renderInlineCodeList
  participant_renderExportCard->>participant_toAnchorId: toAnchorId
  participant_renderExportCard->>participant_escapeAttribute: escapeAttribute
  participant_renderExportCard->>participant_escapeHtml: escapeHtml
  participant_renderExportCard->>participant_renderInlineCodeList: renderInlineCodeList
  participant_renderExportCard->>participant_renderChipList: renderChipList
  participant_renderExportCard->>participant_renderSignatureBlock: renderSignatureBlock
  participant_renderExportCard->>participant_renderMemberTable: renderMemberTable
  participant_renderComponentCard->>participant_toAnchorId: toAnchorId
  participant_renderComponentCard->>participant_escapeAttribute: escapeAttribute
  participant_renderComponentCard->>participant_escapeHtml: escapeHtml
  participant_renderComponentCard->>participant_renderInlineCodeList: renderInlineCodeList
  participant_renderDiagramCard->>participant_escapeAttribute: escapeAttribute
  participant_renderDiagramCard->>participant_escapeHtml: escapeHtml
  participant_groupBy->>participant_key: key
  participant_escapeAttribute->>participant_escapeHtml: escapeHtml
  participant_renderMarkdown->>participant_renderReadme: renderReadme
  participant_renderMarkdown->>participant_renderExports: renderExports
  participant_renderMarkdown->>participant_renderComponents: renderComponents
  participant_src_render_renderers_markdown_ts->>participant_badgeLabel: badgeLabel
  participant_renderReadme->>participant_renderDocumentationTags: renderDocumentationTags
  participant_renderReadme->>participant_renderConfiguration: renderConfiguration
  participant_renderReadme->>participant_renderGeneratedDocumentation: renderGeneratedDocumentation
  participant_renderReadme->>participant_renderArchitecturePreview: renderArchitecturePreview
  participant_renderReadme->>participant_renderPathResolution: renderPathResolution
  participant_renderReadme->>participant_renderReadmeApi: renderReadmeApi
  participant_renderConfiguration->>participant_flattenConfigMembers: flattenConfigMembers
  participant_renderConfiguration->>participant_escapeTableCell: escapeTableCell
  participant_renderConfiguration->>participant_renderDefault: renderDefault
  participant_renderReadmeApi->>participant_getReadmeGroups: getReadmeGroups
  participant_renderReadmeApi->>participant_renderComponentAccordion: renderComponentAccordion
  participant_renderReadmeApi->>participant_renderExportAccordion: renderExportAccordion
  participant_renderComponentAccordion->>participant_renderSignature: renderSignature
  participant_renderComponentAccordion->>participant_renderExamples: renderExamples
  participant_renderComponentAccordion->>participant_escapeTableCell: escapeTableCell
  participant_renderComponentAccordion->>participant_renderDefault: renderDefault
  participant_renderExportAccordion->>participant_renderSignature: renderSignature
  participant_renderExportAccordion->>participant_renderExamples: renderExamples
  participant_getReadmeGroups->>participant_addReadmeItem: addReadmeItem
  participant_getReadmeGroups->>participant_getReadmeCategory: getReadmeCategory
  participant_src_render_renderers_markdown_ts->>participant_sortReadmeItems: sortReadmeItems
  participant_src_render_renderers_markdown_ts->>participant_getReadmeItemName: getReadmeItemName
  participant_renderExports->>participant_escapeTableCell: escapeTableCell
  participant_renderComponents->>participant_escapeTableCell: escapeTableCell
  participant_renderComponents->>participant_renderDefault: renderDefault
  participant_renderDefault->>participant_escapeTableCell: escapeTableCell
  participant_src_render_renderers_markdown_ts->>participant_flattenConfigMembers: flattenConfigMembers
