sequenceDiagram
  participant participant_access as access
  participant participant_addReadmeItem as addReadmeItem
  participant participant_analyze as analyze
  participant participant_analyzeBadges as analyzeBadges
  participant participant_analyzeComponents as analyzeComponents
  participant participant_analyzeExports as analyzeExports
  participant participant_analyzeModules as analyzeModules
  participant participant_analyzeProject as analyzeProject
  participant participant_appendUndefinedIfOptional as appendUndefinedIfOptional
  participant participant_assertPathExists as assertPathExists
  participant participant_assertWithinRoot as assertWithinRoot
  participant participant_associateDocBlocksWithSymbols as associateDocBlocksWithSymbols
  participant participant_badgeLabel as badgeLabel
  participant participant_buildModel as buildModel
  participant participant_collectCallGraph as collectCallGraph
  participant participant_collectComponentCompositionGraph as collectComponentCompositionGraph
  participant participant_collectDefaultValuesFromBinding as collectDefaultValuesFromBinding
  participant participant_collectDocBlocks as collectDocBlocks
  participant participant_collectExports as collectExports
  participant participant_collectImportGraph as collectImportGraph
  participant participant_collectMembersFromType as collectMembersFromType
  participant participant_collectPropsForExport as collectPropsForExport
  participant participant_collectReachableCallEdges as collectReachableCallEdges
  participant participant_collectRelatedSymbols as collectRelatedSymbols
  participant participant_collectRelatedTypes as collectRelatedTypes
  participant participant_collectSequenceParticipants as collectSequenceParticipants
  participant participant_collectSourceFiles as collectSourceFiles
  participant participant_collectTags as collectTags
  participant participant_collectTypeMembers as collectTypeMembers
  participant participant_createEmptyMetadata as createEmptyMetadata
  participant participant_createProject as createProject
  participant participant_createTypeScriptProgram as createTypeScriptProgram
  participant participant_createUsageFromPackageJson as createUsageFromPackageJson
  participant participant_detectExportKind as detectExportKind
  participant participant_dirname as dirname
  participant participant_escapeAttribute as escapeAttribute
  participant participant_escapeHtml as escapeHtml
  participant participant_escapeLabel as escapeLabel
  participant participant_escapeRegExp as escapeRegExp
  participant participant_escapeTableCell as escapeTableCell
  participant participant_escapeXml as escapeXml
  participant participant_fileExists as fileExists
  participant participant_findConfigFactoryName as findConfigFactoryName
  participant participant_findJsxElements as findJsxElements
  participant participant_findParadoxConfigFile as findParadoxConfigFile
  participant participant_flattenConfigMembers as flattenConfigMembers
  participant participant_flattenMembers as flattenMembers
  participant participant_formatCallLabel as formatCallLabel
  participant participant_formatPercent as formatPercent
  participant participant_getBadgeOrder as getBadgeOrder
  participant participant_getCallableDeclarations as getCallableDeclarations
  participant participant_getCallableNode as getCallableNode
  participant participant_getCallEdgeKey as getCallEdgeKey
  participant participant_getCallFlowRoots as getCallFlowRoots
  participant participant_getCallSignature as getCallSignature
  participant participant_getComponentPropsType as getComponentPropsType
  participant participant_getCoverageColor as getCoverageColor
  participant participant_getDeclarationName as getDeclarationName
  participant participant_getDeclaredMembers as getDeclaredMembers
  participant participant_getDeclaredTypeText as getDeclaredTypeText
  participant participant_getDefaultConfigFileName as getDefaultConfigFileName
  participant participant_getEnclosingSymbolName as getEnclosingSymbolName
  participant participant_getEntryPointSourceFiles as getEntryPointSourceFiles
  participant participant_getExportMetadata as getExportMetadata
  participant participant_getExportSignature as getExportSignature
  participant participant_getFirstDeclaration as getFirstDeclaration
  participant participant_getMembers as getMembers
  participant participant_getMembersFromProperties as getMembersFromProperties
  participant participant_getPackageBaseName as getPackageBaseName
  participant participant_getParadoxComment as getParadoxComment
  participant participant_getParameterTypeText as getParameterTypeText
  participant participant_getPropsFromType as getPropsFromType
  participant participant_getReadmeCategory as getReadmeCategory
  participant participant_getReadmeGroups as getReadmeGroups
  participant participant_getReadmeItemName as getReadmeItemName
  participant participant_getSignature as getSignature
  participant participant_getSignatures as getSignatures
  participant participant_getSourceLocation as getSourceLocation
  participant participant_getTextWidth as getTextWidth
  participant participant_groupBy as groupBy
  participant participant_groupCallsBySource as groupCallsBySource
  participant participant_hasAnyFile as hasAnyFile
  participant participant_hasScript as hasScript
  participant participant_hasTypeScriptStrictMode as hasTypeScriptStrictMode
  participant participant_inferKind as inferKind
  participant participant_isAbsolute as isAbsolute
  participant participant_isMemberMethodDeclaration as isMemberMethodDeclaration
  participant participant_isNodeModulePath as isNodeModulePath
  participant participant_isNotFoundError as isNotFoundError
  participant participant_isPathInsideRoot as isPathInsideRoot
  participant participant_isReactComponent as isReactComponent
  participant participant_isUndefinedUnion as isUndefinedUnion
  participant participant_join as join
  participant participant_key as key
  participant participant_loadParadoxConfig as loadParadoxConfig
  participant participant_main as main
  participant participant_mapComponent as mapComponent
  participant participant_mapExport as mapExport
  participant participant_mapTypeMembers as mapTypeMembers
  participant participant_mkdir as mkdir
  participant participant_normalize as normalize
  participant participant_normalizeCommentLines as normalizeCommentLines
  participant participant_normalizeDocBlock as normalizeDocBlock
  participant participant_parseDocBlock as parseDocBlock
  participant participant_parseExample as parseExample
  participant participant_parseParadoxComment as parseParadoxComment
  participant participant_pathExists as pathExists
  participant participant_pathToFileURL as pathToFileURL
  participant participant_readCoveragePercent as readCoveragePercent
  participant participant_readdir as readdir
  participant participant_readDirectory as readDirectory
  participant participant_readFile as readFile
  participant participant_readJsonFile as readJsonFile
  participant participant_readPackageJson as readPackageJson
  participant participant_readParadoxMetadata as readParadoxMetadata
  participant participant_readWorkflowFiles as readWorkflowFiles
  participant participant_relative as relative
  participant participant_relativeToRoot as relativeToRoot
  participant participant_render as render
  participant participant_renderArchitectureOverview as renderArchitectureOverview
  participant participant_renderArchitecturePreview as renderArchitecturePreview
  participant participant_renderBadgeArtifacts as renderBadgeArtifacts
  participant participant_renderBadgeSvg as renderBadgeSvg
  participant participant_renderCallFlow as renderCallFlow
  participant participant_renderChipList as renderChipList
  participant participant_renderComponentAccordion as renderComponentAccordion
  participant participant_renderComponentCard as renderComponentCard
  participant participant_renderComponents as renderComponents
  participant participant_renderConfiguration as renderConfiguration
  participant participant_renderDefault as renderDefault
  participant participant_renderDiagramArtifacts as renderDiagramArtifacts
  participant participant_renderDiagramCard as renderDiagramCard
  participant participant_renderDocumentationTags as renderDocumentationTags
  participant participant_renderEntrypointSequence as renderEntrypointSequence
  participant participant_renderer as renderer
  participant participant_renderExamples as renderExamples
  participant participant_renderExportAccordion as renderExportAccordion
  participant participant_renderExportCard as renderExportCard
  participant participant_renderExportGraph as renderExportGraph
  participant participant_renderExports as renderExports
  participant participant_renderFallbackEdge as renderFallbackEdge
  participant participant_renderGeneratedDocumentation as renderGeneratedDocumentation
  participant participant_renderHtml as renderHtml
  participant participant_renderInlineCodeList as renderInlineCodeList
  participant participant_renderMarkdown as renderMarkdown
  participant participant_renderMemberTable as renderMemberTable
  participant participant_renderModuleCard as renderModuleCard
  participant participant_renderModuleRelationships as renderModuleRelationships
  participant participant_renderNestedCalls as renderNestedCalls
  participant participant_renderPathResolution as renderPathResolution
  participant participant_renderReadme as renderReadme
  participant participant_renderReadmeApi as renderReadmeApi
  participant participant_renderSignature as renderSignature
  participant participant_renderSignatureBlock as renderSignatureBlock
  participant participant_resolve as resolve
  participant participant_resolveExportSymbol as resolveExportSymbol
  participant participant_resolveOutputRoot as resolveOutputRoot
  participant participant_resolvePackageRoot as resolvePackageRoot
  participant participant_resolveTypeReference as resolveTypeReference
  participant participant_scriptContains as scriptContains
  participant participant_shouldExpandType as shouldExpandType
  participant participant_sortBadges as sortBadges
  participant participant_sortByName as sortByName
  participant participant_sortReadmeItems as sortReadmeItems
  participant participant_splitPathSegments as splitPathSegments
  participant participant_src_analyze_analyze_ts as src/analyze/analyze.ts
  participant participant_src_analyze_badges_ts as src/analyze/badges.ts
  participant participant_src_analyze_exports_ts as src/analyze/exports.ts
  participant participant_src_analyze_modules_ts as src/analyze/modules.ts
  participant participant_src_analyze_semantic_analyzeProject_ts as src/analyze/semantic/analyzeProject.ts
  participant participant_src_analyze_semantic_associateDocBlocksWithSymbols_ts as src/analyze/semantic/associateDocBlocksWithSymbols.ts
  participant participant_src_analyze_semantic_collectSourceFiles_ts as src/analyze/semantic/collectSourceFiles.ts
  participant participant_src_analyze_semantic_createTypeScriptProgram_ts as src/analyze/semantic/createTypeScriptProgram.ts
  participant participant_src_analyze_semantic_exports_ts as src/analyze/semantic/exports.ts
  participant participant_src_analyze_semantic_graphs_ts as src/analyze/semantic/graphs.ts
  participant participant_src_analyze_utils_getExportMetadata_ts as src/analyze/utils/getExportMetadata.ts
  participant participant_src_analyze_utils_getPropsFromType_ts as src/analyze/utils/getPropsFromType.ts
  participant participant_src_cli_ts as src/cli.ts
  participant participant_src_model_buildModel_ts as src/model/buildModel.ts
  participant participant_src_render_renderers_badges_ts as src/render/renderers/badges.ts
  participant participant_src_render_renderers_diagrams_ts as src/render/renderers/diagrams.ts
  participant participant_src_render_renderers_html_ts as src/render/renderers/html.ts
  participant participant_src_render_renderers_markdown_ts as src/render/renderers/markdown.ts
  participant participant_supportsBun as supportsBun
  participant participant_toAnchorId as toAnchorId
  participant participant_toCallEdge as toCallEdge
  participant participant_toMermaidId as toMermaidId
  participant participant_toPosixPath as toPosixPath
  participant participant_uniqueBy as uniqueBy
  participant participant_uniqueEdges as uniqueEdges
  participant participant_uniqueSorted as uniqueSorted
  participant participant_validateOutputDir as validateOutputDir
  participant participant_visitCallEdges as visitCallEdges
  participant participant_workflowRunsScript as workflowRunsScript
  participant participant_write as write
  participant participant_writeFile as writeFile
  participant_analyzeProject->>participant_createTypeScriptProgram: createTypeScriptProgram()
  participant_createTypeScriptProgram->>participant_normalize: normalize()
  participant_normalize-->>participant_createTypeScriptProgram: return
  participant_createTypeScriptProgram->>participant_join: join()
  participant_join-->>participant_createTypeScriptProgram: return
  participant_createTypeScriptProgram-->>participant_analyzeProject: return
  participant_analyzeProject->>participant_collectSourceFiles: collectSourceFiles()
  participant_collectSourceFiles-->>participant_analyzeProject: return
  participant_analyzeProject->>participant_associateDocBlocksWithSymbols: associateDocBlocksWithSymbols()
  participant_associateDocBlocksWithSymbols-->>participant_analyzeProject: return
  participant_analyzeProject->>participant_collectExports: collectExports()
  participant_collectExports->>participant_relativeToRoot: relativeToRoot()
  participant_relativeToRoot->>participant_toPosixPath: toPosixPath()
  participant_toPosixPath-->>participant_relativeToRoot: return
  participant_relativeToRoot->>participant_relative: relative()
  participant_relative-->>participant_relativeToRoot: return
  participant_relativeToRoot-->>participant_collectExports: return
  participant_collectExports->>participant_resolveExportSymbol: resolveExportSymbol()
  participant_resolveExportSymbol-->>participant_collectExports: return
  participant_collectExports->>participant_getFirstDeclaration: getFirstDeclaration()
  participant_getFirstDeclaration-->>participant_collectExports: return
  participant_collectExports->>participant_uniqueSorted: uniqueSorted()
  participant_uniqueSorted-->>participant_collectExports: return
  participant_collectExports->>participant_detectExportKind: detectExportKind()
  participant_detectExportKind->>participant_isReactComponent: isReactComponent()
  participant_isReactComponent->>participant_getDeclarationName: getDeclarationName()
  participant_getDeclarationName-->>participant_isReactComponent: return
  participant_isReactComponent->>participant_getCallSignature: getCallSignature()
  participant_getCallSignature-->>participant_isReactComponent: return
  participant_isReactComponent->>participant_getDeclarationName: getDeclarationName()
  participant_getDeclarationName-->>participant_isReactComponent: return
  participant_isReactComponent->>participant_getCallSignature: getCallSignature()
  participant_getCallSignature-->>participant_isReactComponent: return
  participant_isReactComponent-->>participant_detectExportKind: return
  participant_detectExportKind->>participant_getDeclarationName: getDeclarationName()
  participant_getDeclarationName-->>participant_detectExportKind: return
  participant_detectExportKind-->>participant_collectExports: return
  participant_collectExports-->>participant_analyzeProject: return
  participant_analyzeProject->>participant_collectImportGraph: collectImportGraph()
  participant_collectImportGraph->>participant_isPathInsideRoot: isPathInsideRoot()
  participant_isPathInsideRoot->>participant_normalize: normalize()
  participant_normalize-->>participant_isPathInsideRoot: return
  participant_isPathInsideRoot-->>participant_collectImportGraph: return
  participant_collectImportGraph->>participant_isNodeModulePath: isNodeModulePath()
  participant_isNodeModulePath->>participant_toPosixPath: toPosixPath()
  participant_toPosixPath-->>participant_isNodeModulePath: return
  participant_isNodeModulePath-->>participant_collectImportGraph: return
  participant_collectImportGraph->>participant_relativeToRoot: relativeToRoot()
  participant_relativeToRoot-->>participant_collectImportGraph: return
  participant_collectImportGraph->>participant_uniqueEdges: uniqueEdges()
  participant_uniqueEdges-->>participant_collectImportGraph: return
  participant_collectImportGraph-->>participant_analyzeProject: return
  participant_analyzeProject->>participant_collectCallGraph: collectCallGraph()
  participant_collectCallGraph->>participant_isPathInsideRoot: isPathInsideRoot()
  participant_isPathInsideRoot-->>participant_collectCallGraph: return
  participant_collectCallGraph->>participant_isNodeModulePath: isNodeModulePath()
  participant_isNodeModulePath-->>participant_collectCallGraph: return
  participant_collectCallGraph->>participant_relativeToRoot: relativeToRoot()
  participant_relativeToRoot-->>participant_collectCallGraph: return
  participant_collectCallGraph->>participant_uniqueEdges: uniqueEdges()
  participant_uniqueEdges-->>participant_collectCallGraph: return
  participant_collectCallGraph-->>participant_analyzeProject: return
  participant_analyzeProject->>participant_collectComponentCompositionGraph: collectComponentCompositionGraph()
  participant_collectComponentCompositionGraph->>participant_collectExports: collectExports()
  participant_collectExports-->>participant_collectComponentCompositionGraph: return
  participant_collectComponentCompositionGraph->>participant_findJsxElements: findJsxElements()
  participant_findJsxElements-->>participant_collectComponentCompositionGraph: return
  participant_collectComponentCompositionGraph->>participant_uniqueEdges: uniqueEdges()
  participant_uniqueEdges-->>participant_collectComponentCompositionGraph: return
  participant_collectComponentCompositionGraph-->>participant_analyzeProject: return
  participant_renderComponentCard->>participant_toAnchorId: toAnchorId()
  participant_toAnchorId-->>participant_renderComponentCard: return
  participant_renderComponentCard->>participant_escapeAttribute: escapeAttribute()
  participant_escapeAttribute->>participant_escapeHtml: escapeHtml()
  participant_escapeHtml-->>participant_escapeAttribute: return
  participant_escapeAttribute-->>participant_renderComponentCard: return
  participant_renderComponentCard->>participant_escapeHtml: escapeHtml()
  participant_escapeHtml-->>participant_renderComponentCard: return
  participant_renderComponentCard->>participant_renderInlineCodeList: renderInlineCodeList()
  participant_renderInlineCodeList-->>participant_renderComponentCard: return
  participant_renderDiagramCard->>participant_escapeAttribute: escapeAttribute()
  participant_escapeAttribute-->>participant_renderDiagramCard: return
  participant_renderDiagramCard->>participant_escapeHtml: escapeHtml()
  participant_escapeHtml-->>participant_renderDiagramCard: return
  participant_renderHtml->>participant_groupBy: groupBy()
  participant_groupBy->>participant_key: key()
  participant_key-->>participant_groupBy: return
  participant_groupBy-->>participant_renderHtml: return
  participant_renderHtml->>participant_escapeHtml: escapeHtml()
  participant_escapeHtml-->>participant_renderHtml: return
  participant_renderMarkdown->>participant_renderReadme: renderReadme()
  participant_renderReadme->>participant_renderDocumentationTags: renderDocumentationTags()
  participant_renderDocumentationTags-->>participant_renderReadme: return
  participant_renderReadme->>participant_renderConfiguration: renderConfiguration()
  participant_renderConfiguration->>participant_flattenConfigMembers: flattenConfigMembers()
  participant_flattenConfigMembers-->>participant_renderConfiguration: return
  participant_renderConfiguration->>participant_escapeTableCell: escapeTableCell()
  participant_escapeTableCell-->>participant_renderConfiguration: return
  participant_renderConfiguration->>participant_renderDefault: renderDefault()
  participant_renderDefault->>participant_escapeTableCell: escapeTableCell()
  participant_escapeTableCell-->>participant_renderDefault: return
  participant_renderDefault-->>participant_renderConfiguration: return
  participant_renderConfiguration-->>participant_renderReadme: return
  participant_renderReadme->>participant_renderGeneratedDocumentation: renderGeneratedDocumentation()
  participant_renderGeneratedDocumentation-->>participant_renderReadme: return
  participant_renderReadme->>participant_renderArchitecturePreview: renderArchitecturePreview()
  participant_renderArchitecturePreview-->>participant_renderReadme: return
  participant_renderReadme->>participant_renderPathResolution: renderPathResolution()
  participant_renderPathResolution-->>participant_renderReadme: return
  participant_renderReadme->>participant_renderReadmeApi: renderReadmeApi()
  participant_renderReadmeApi->>participant_getReadmeGroups: getReadmeGroups()
  participant_getReadmeGroups->>participant_addReadmeItem: addReadmeItem()
  participant_addReadmeItem-->>participant_getReadmeGroups: return
  participant_getReadmeGroups->>participant_getReadmeCategory: getReadmeCategory()
  participant_getReadmeCategory-->>participant_getReadmeGroups: return
  participant_getReadmeGroups-->>participant_renderReadmeApi: return
  participant_renderReadmeApi->>participant_renderComponentAccordion: renderComponentAccordion()
  participant_renderComponentAccordion->>participant_renderSignature: renderSignature()
  participant_renderSignature-->>participant_renderComponentAccordion: return
  participant_renderComponentAccordion->>participant_renderExamples: renderExamples()
  participant_renderExamples-->>participant_renderComponentAccordion: return
  participant_renderComponentAccordion->>participant_escapeTableCell: escapeTableCell()
  participant_escapeTableCell-->>participant_renderComponentAccordion: return
  participant_renderComponentAccordion->>participant_renderDefault: renderDefault()
  participant_renderDefault-->>participant_renderComponentAccordion: return
  participant_renderComponentAccordion-->>participant_renderReadmeApi: return
  participant_renderReadmeApi->>participant_renderExportAccordion: renderExportAccordion()
  participant_renderExportAccordion->>participant_renderSignature: renderSignature()
  participant_renderSignature-->>participant_renderExportAccordion: return
  participant_renderExportAccordion->>participant_renderExamples: renderExamples()
  participant_renderExamples-->>participant_renderExportAccordion: return
  participant_renderExportAccordion-->>participant_renderReadmeApi: return
  participant_renderReadmeApi-->>participant_renderReadme: return
  participant_renderReadme-->>participant_renderMarkdown: return
  participant_renderMarkdown->>participant_renderExports: renderExports()
  participant_renderExports->>participant_escapeTableCell: escapeTableCell()
  participant_escapeTableCell-->>participant_renderExports: return
  participant_renderExports-->>participant_renderMarkdown: return
  participant_renderMarkdown->>participant_renderComponents: renderComponents()
  participant_renderComponents->>participant_escapeTableCell: escapeTableCell()
  participant_escapeTableCell-->>participant_renderComponents: return
  participant_renderComponents->>participant_renderDefault: renderDefault()
  participant_renderDefault-->>participant_renderComponents: return
  participant_renderComponents-->>participant_renderMarkdown: return
  participant_renderModuleCard->>participant_escapeAttribute: escapeAttribute()
  participant_escapeAttribute-->>participant_renderModuleCard: return
  participant_renderModuleCard->>participant_escapeHtml: escapeHtml()
  participant_escapeHtml-->>participant_renderModuleCard: return
  participant_renderModuleCard->>participant_renderInlineCodeList: renderInlineCodeList()
  participant_renderInlineCodeList-->>participant_renderModuleCard: return
  participant_src_analyze_analyze_ts->>participant_mapTypeMembers: mapTypeMembers()
  participant_mapTypeMembers-->>participant_src_analyze_analyze_ts: return
  participant_src_analyze_badges_ts->>participant_readFile: readFile()
  participant_readFile-->>participant_src_analyze_badges_ts: return
  participant_src_analyze_badges_ts->>participant_join: join()
  participant_join-->>participant_src_analyze_badges_ts: return
  participant_src_analyze_badges_ts->>participant_getBadgeOrder: getBadgeOrder()
  participant_getBadgeOrder-->>participant_src_analyze_badges_ts: return
  participant_src_analyze_exports_ts->>participant_normalize: normalize()
  participant_normalize-->>participant_src_analyze_exports_ts: return
  participant_src_analyze_exports_ts->>participant_isAbsolute: isAbsolute()
  participant_isAbsolute-->>participant_src_analyze_exports_ts: return
  participant_src_analyze_exports_ts->>participant_join: join()
  participant_join-->>participant_src_analyze_exports_ts: return
  participant_src_analyze_modules_ts->>participant_normalize: normalize()
  participant_normalize-->>participant_src_analyze_modules_ts: return
  participant_src_analyze_modules_ts->>participant_isAbsolute: isAbsolute()
  participant_isAbsolute-->>participant_src_analyze_modules_ts: return
  participant_src_analyze_modules_ts->>participant_join: join()
  participant_join-->>participant_src_analyze_modules_ts: return
  participant_src_analyze_modules_ts->>participant_toPosixPath: toPosixPath()
  participant_toPosixPath-->>participant_src_analyze_modules_ts: return
  participant_src_analyze_modules_ts->>participant_relative: relative()
  participant_relative-->>participant_src_analyze_modules_ts: return
  participant_src_analyze_modules_ts->>participant_uniqueSorted: uniqueSorted()
  participant_uniqueSorted-->>participant_src_analyze_modules_ts: return
  participant_src_analyze_semantic_analyzeProject_ts->>participant_collectDocBlocks: collectDocBlocks()
  participant_collectDocBlocks->>participant_relativeToRoot: relativeToRoot()
  participant_relativeToRoot-->>participant_collectDocBlocks: return
  participant_collectDocBlocks->>participant_parseDocBlock: parseDocBlock()
  participant_parseDocBlock->>participant_normalizeDocBlock: normalizeDocBlock()
  participant_normalizeDocBlock-->>participant_parseDocBlock: return
  participant_parseDocBlock->>participant_collectTags: collectTags()
  participant_collectTags->>participant_normalizeDocBlock: normalizeDocBlock()
  participant_normalizeDocBlock-->>participant_collectTags: return
  participant_collectTags-->>participant_parseDocBlock: return
  participant_parseDocBlock-->>participant_collectDocBlocks: return
  participant_collectDocBlocks-->>participant_src_analyze_semantic_analyzeProject_ts: return
  participant_src_analyze_semantic_analyzeProject_ts->>participant_getExportSignature: getExportSignature()
  participant_getExportSignature->>participant_getCallableNode: getCallableNode()
  participant_getCallableNode-->>participant_getExportSignature: return
  participant_getExportSignature-->>participant_src_analyze_semantic_analyzeProject_ts: return
  participant_src_analyze_semantic_analyzeProject_ts->>participant_collectPropsForExport: collectPropsForExport()
  participant_collectPropsForExport->>participant_getCallableNode: getCallableNode()
  participant_getCallableNode-->>participant_collectPropsForExport: return
  participant_collectPropsForExport->>participant_resolveTypeReference: resolveTypeReference()
  participant_resolveTypeReference->>participant_getFirstDeclaration: getFirstDeclaration()
  participant_getFirstDeclaration-->>participant_resolveTypeReference: return
  participant_resolveTypeReference->>participant_relativeToRoot: relativeToRoot()
  participant_relativeToRoot-->>participant_resolveTypeReference: return
  participant_resolveTypeReference-->>participant_collectPropsForExport: return
  participant_collectPropsForExport->>participant_collectDefaultValuesFromBinding: collectDefaultValuesFromBinding()
  participant_collectDefaultValuesFromBinding-->>participant_collectPropsForExport: return
  participant_collectPropsForExport->>participant_collectTypeMembers: collectTypeMembers()
  participant_collectTypeMembers->>participant_collectMembersFromType: collectMembersFromType()
  participant_collectMembersFromType->>participant_getDeclaredMembers: getDeclaredMembers()
  participant_getDeclaredMembers-->>participant_collectMembersFromType: return
  participant_collectMembersFromType-->>participant_collectTypeMembers: return
  participant_collectTypeMembers->>participant_resolveTypeReference: resolveTypeReference()
  participant_resolveTypeReference-->>participant_collectTypeMembers: return
  participant_collectTypeMembers->>participant_collectTypeMembers: collectTypeMembers()
  participant_collectTypeMembers-->>participant_collectTypeMembers: return
  participant_collectTypeMembers-->>participant_collectPropsForExport: return
  participant_collectPropsForExport-->>participant_src_analyze_semantic_analyzeProject_ts: return
  participant_src_analyze_semantic_analyzeProject_ts->>participant_resolveTypeReference: resolveTypeReference()
  participant_resolveTypeReference-->>participant_src_analyze_semantic_analyzeProject_ts: return
  participant_src_analyze_semantic_analyzeProject_ts->>participant_collectTypeMembers: collectTypeMembers()
  participant_collectTypeMembers-->>participant_src_analyze_semantic_analyzeProject_ts: return
  participant_src_analyze_semantic_analyzeProject_ts->>participant_collectRelatedTypes: collectRelatedTypes()
  participant_collectRelatedTypes->>participant_flattenMembers: flattenMembers()
  participant_flattenMembers-->>participant_collectRelatedTypes: return
  participant_collectRelatedTypes-->>participant_src_analyze_semantic_analyzeProject_ts: return
  participant_src_analyze_semantic_associateDocBlocksWithSymbols_ts->>participant_relativeToRoot: relativeToRoot()
  participant_relativeToRoot-->>participant_src_analyze_semantic_associateDocBlocksWithSymbols_ts: return
  participant_src_analyze_semantic_collectSourceFiles_ts->>participant_normalize: normalize()
  participant_normalize-->>participant_src_analyze_semantic_collectSourceFiles_ts: return
  participant_src_analyze_semantic_collectSourceFiles_ts->>participant_isPathInsideRoot: isPathInsideRoot()
  participant_isPathInsideRoot-->>participant_src_analyze_semantic_collectSourceFiles_ts: return
  participant_src_analyze_semantic_collectSourceFiles_ts->>participant_isNodeModulePath: isNodeModulePath()
  participant_isNodeModulePath-->>participant_src_analyze_semantic_collectSourceFiles_ts: return
  participant_src_analyze_semantic_collectSourceFiles_ts->>participant_relativeToRoot: relativeToRoot()
  participant_relativeToRoot-->>participant_src_analyze_semantic_collectSourceFiles_ts: return
  participant_src_analyze_semantic_createTypeScriptProgram_ts->>participant_normalize: normalize()
  participant_normalize-->>participant_src_analyze_semantic_createTypeScriptProgram_ts: return
  participant_src_analyze_semantic_createTypeScriptProgram_ts->>participant_isAbsolute: isAbsolute()
  participant_isAbsolute-->>participant_src_analyze_semantic_createTypeScriptProgram_ts: return
  participant_src_analyze_semantic_createTypeScriptProgram_ts->>participant_join: join()
  participant_join-->>participant_src_analyze_semantic_createTypeScriptProgram_ts: return
  participant_src_analyze_semantic_createTypeScriptProgram_ts->>participant_toPosixPath: toPosixPath()
  participant_toPosixPath-->>participant_src_analyze_semantic_createTypeScriptProgram_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_getFirstDeclaration: getFirstDeclaration()
  participant_getFirstDeclaration-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_getParameterTypeText: getParameterTypeText()
  participant_getParameterTypeText-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_getParadoxComment: getParadoxComment()
  participant_getParadoxComment-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_parseParadoxComment: parseParadoxComment()
  participant_parseParadoxComment->>participant_normalizeCommentLines: normalizeCommentLines()
  participant_normalizeCommentLines-->>participant_parseParadoxComment: return
  participant_parseParadoxComment->>participant_parseExample: parseExample()
  participant_parseExample-->>participant_parseParadoxComment: return
  participant_parseParadoxComment-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_isUndefinedUnion: isUndefinedUnion()
  participant_isUndefinedUnion-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_shouldExpandType: shouldExpandType()
  participant_shouldExpandType->>participant_getFirstDeclaration: getFirstDeclaration()
  participant_getFirstDeclaration-->>participant_shouldExpandType: return
  participant_shouldExpandType->>participant_relativeToRoot: relativeToRoot()
  participant_relativeToRoot-->>participant_shouldExpandType: return
  participant_shouldExpandType-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_resolveTypeReference: resolveTypeReference()
  participant_resolveTypeReference-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_collectTypeMembers: collectTypeMembers()
  participant_collectTypeMembers-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_getDeclaredTypeText: getDeclaredTypeText()
  participant_getDeclaredTypeText-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_appendUndefinedIfOptional: appendUndefinedIfOptional()
  participant_appendUndefinedIfOptional-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_isPathInsideRoot: isPathInsideRoot()
  participant_isPathInsideRoot-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_isNodeModulePath: isNodeModulePath()
  participant_isNodeModulePath-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_exports_ts->>participant_flattenMembers: flattenMembers()
  participant_flattenMembers-->>participant_src_analyze_semantic_exports_ts: return
  participant_src_analyze_semantic_graphs_ts->>participant_toCallEdge: toCallEdge()
  participant_toCallEdge->>participant_isPathInsideRoot: isPathInsideRoot()
  participant_isPathInsideRoot-->>participant_toCallEdge: return
  participant_toCallEdge->>participant_isNodeModulePath: isNodeModulePath()
  participant_isNodeModulePath-->>participant_toCallEdge: return
  participant_toCallEdge->>participant_getEnclosingSymbolName: getEnclosingSymbolName()
  participant_getEnclosingSymbolName-->>participant_toCallEdge: return
  participant_toCallEdge-->>participant_src_analyze_semantic_graphs_ts: return
  participant_src_analyze_semantic_graphs_ts->>participant_key: key()
  participant_key-->>participant_src_analyze_semantic_graphs_ts: return
  participant_src_analyze_utils_getExportMetadata_ts->>participant_getSignature: getSignature()
  participant_getSignature-->>participant_src_analyze_utils_getExportMetadata_ts: return
  participant_src_analyze_utils_getExportMetadata_ts->>participant_getFirstDeclaration: getFirstDeclaration()
  participant_getFirstDeclaration-->>participant_src_analyze_utils_getExportMetadata_ts: return
  participant_src_analyze_utils_getExportMetadata_ts->>participant_getParadoxComment: getParadoxComment()
  participant_getParadoxComment-->>participant_src_analyze_utils_getExportMetadata_ts: return
  participant_src_analyze_utils_getExportMetadata_ts->>participant_parseParadoxComment: parseParadoxComment()
  participant_parseParadoxComment-->>participant_src_analyze_utils_getExportMetadata_ts: return
  participant_src_analyze_utils_getExportMetadata_ts->>participant_isMemberMethodDeclaration: isMemberMethodDeclaration()
  participant_isMemberMethodDeclaration-->>participant_src_analyze_utils_getExportMetadata_ts: return
  participant_src_analyze_utils_getExportMetadata_ts->>participant_getCallableNode: getCallableNode()
  participant_getCallableNode-->>participant_src_analyze_utils_getExportMetadata_ts: return
  participant_src_analyze_utils_getExportMetadata_ts->>participant_key: key()
  participant_key-->>participant_src_analyze_utils_getExportMetadata_ts: return
  participant_src_analyze_utils_getPropsFromType_ts->>participant_getParadoxComment: getParadoxComment()
  participant_getParadoxComment-->>participant_src_analyze_utils_getPropsFromType_ts: return
  participant_src_analyze_utils_getPropsFromType_ts->>participant_parseParadoxComment: parseParadoxComment()
  participant_parseParadoxComment-->>participant_src_analyze_utils_getPropsFromType_ts: return
  participant_src_cli_ts->>participant_main: main()
  participant_main->>participant_findParadoxConfigFile: findParadoxConfigFile()
  participant_findParadoxConfigFile->>participant_resolve: resolve()
  participant_resolve-->>participant_findParadoxConfigFile: return
  participant_findParadoxConfigFile->>participant_dirname: dirname()
  participant_dirname-->>participant_findParadoxConfigFile: return
  participant_findParadoxConfigFile->>participant_join: join()
  participant_join-->>participant_findParadoxConfigFile: return
  participant_findParadoxConfigFile->>participant_pathExists: pathExists()
  participant_pathExists->>participant_access: access()
  participant_access-->>participant_pathExists: return
  participant_pathExists-->>participant_findParadoxConfigFile: return
  participant_findParadoxConfigFile-->>participant_main: return
  participant_main->>participant_dirname: dirname()
  participant_dirname-->>participant_main: return
  participant_main->>participant_loadParadoxConfig: loadParadoxConfig()
  participant_loadParadoxConfig->>participant_pathToFileURL: pathToFileURL()
  participant_pathToFileURL-->>participant_loadParadoxConfig: return
  participant_loadParadoxConfig-->>participant_main: return
  participant_main->>participant_resolvePackageRoot: resolvePackageRoot()
  participant_resolvePackageRoot->>participant_isAbsolute: isAbsolute()
  participant_isAbsolute-->>participant_resolvePackageRoot: return
  participant_resolvePackageRoot->>participant_resolve: resolve()
  participant_resolve-->>participant_resolvePackageRoot: return
  participant_resolvePackageRoot->>participant_assertPathExists: assertPathExists()
  participant_assertPathExists->>participant_pathExists: pathExists()
  participant_pathExists-->>participant_assertPathExists: return
  participant_assertPathExists-->>participant_resolvePackageRoot: return
  participant_resolvePackageRoot->>participant_join: join()
  participant_join-->>participant_resolvePackageRoot: return
  participant_resolvePackageRoot-->>participant_main: return
  participant_main->>participant_resolveOutputRoot: resolveOutputRoot()
  participant_resolveOutputRoot->>participant_validateOutputDir: validateOutputDir()
  participant_validateOutputDir->>participant_normalize: normalize()
  participant_normalize-->>participant_validateOutputDir: return
  participant_validateOutputDir->>participant_isAbsolute: isAbsolute()
  participant_isAbsolute-->>participant_validateOutputDir: return
  participant_validateOutputDir->>participant_splitPathSegments: splitPathSegments()
  participant_splitPathSegments-->>participant_validateOutputDir: return
  participant_validateOutputDir-->>participant_resolveOutputRoot: return
  participant_resolveOutputRoot->>participant_resolve: resolve()
  participant_resolve-->>participant_resolveOutputRoot: return
  participant_resolveOutputRoot->>participant_assertWithinRoot: assertWithinRoot()
  participant_assertWithinRoot->>participant_relative: relative()
  participant_relative-->>participant_assertWithinRoot: return
  participant_assertWithinRoot-->>participant_resolveOutputRoot: return
  participant_resolveOutputRoot-->>participant_main: return
  participant_main->>participant_analyze: analyze()
  participant_analyze->>participant_readPackageJson: readPackageJson()
  participant_readPackageJson->>participant_readFile: readFile()
  participant_readFile-->>participant_readPackageJson: return
  participant_readPackageJson->>participant_join: join()
  participant_join-->>participant_readPackageJson: return
  participant_readPackageJson-->>participant_analyze: return
  participant_analyze->>participant_createUsageFromPackageJson: createUsageFromPackageJson()
  participant_createUsageFromPackageJson->>participant_getPackageBaseName: getPackageBaseName()
  participant_getPackageBaseName-->>participant_createUsageFromPackageJson: return
  participant_createUsageFromPackageJson-->>participant_analyze: return
  participant_analyze->>participant_analyzeBadges: analyzeBadges()
  participant_analyzeBadges->>participant_readWorkflowFiles: readWorkflowFiles()
  participant_readWorkflowFiles->>participant_join: join()
  participant_join-->>participant_readWorkflowFiles: return
  participant_readWorkflowFiles->>participant_readDirectory: readDirectory()
  participant_readDirectory->>participant_readdir: readdir()
  participant_readdir-->>participant_readDirectory: return
  participant_readDirectory->>participant_isNotFoundError: isNotFoundError()
  participant_isNotFoundError-->>participant_readDirectory: return
  participant_readDirectory-->>participant_readWorkflowFiles: return
  participant_readWorkflowFiles-->>participant_analyzeBadges: return
  participant_analyzeBadges->>participant_hasAnyFile: hasAnyFile()
  participant_hasAnyFile->>participant_fileExists: fileExists()
  participant_fileExists->>participant_access: access()
  participant_access-->>participant_fileExists: return
  participant_fileExists->>participant_isNotFoundError: isNotFoundError()
  participant_isNotFoundError-->>participant_fileExists: return
  participant_fileExists-->>participant_hasAnyFile: return
  participant_hasAnyFile->>participant_join: join()
  participant_join-->>participant_hasAnyFile: return
  participant_hasAnyFile-->>participant_analyzeBadges: return
  participant_analyzeBadges->>participant_scriptContains: scriptContains()
  participant_scriptContains-->>participant_analyzeBadges: return
  participant_analyzeBadges->>participant_workflowRunsScript: workflowRunsScript()
  participant_workflowRunsScript->>participant_escapeRegExp: escapeRegExp()
  participant_escapeRegExp-->>participant_workflowRunsScript: return
  participant_workflowRunsScript-->>participant_analyzeBadges: return
  participant_analyzeBadges->>participant_hasScript: hasScript()
  participant_hasScript-->>participant_analyzeBadges: return
  participant_analyzeBadges->>participant_hasTypeScriptStrictMode: hasTypeScriptStrictMode()
  participant_hasTypeScriptStrictMode->>participant_readJsonFile: readJsonFile()
  participant_readJsonFile->>participant_readFile: readFile()
  participant_readFile-->>participant_readJsonFile: return
  participant_readJsonFile->>participant_isNotFoundError: isNotFoundError()
  participant_isNotFoundError-->>participant_readJsonFile: return
  participant_readJsonFile-->>participant_hasTypeScriptStrictMode: return
  participant_hasTypeScriptStrictMode->>participant_join: join()
  participant_join-->>participant_hasTypeScriptStrictMode: return
  participant_hasTypeScriptStrictMode-->>participant_analyzeBadges: return
  participant_analyzeBadges->>participant_supportsBun: supportsBun()
  participant_supportsBun-->>participant_analyzeBadges: return
  participant_analyzeBadges->>participant_readCoveragePercent: readCoveragePercent()
  participant_readCoveragePercent->>participant_readJsonFile: readJsonFile()
  participant_readJsonFile-->>participant_readCoveragePercent: return
  participant_readCoveragePercent->>participant_join: join()
  participant_join-->>participant_readCoveragePercent: return
  participant_readCoveragePercent-->>participant_analyzeBadges: return
  participant_analyzeBadges->>participant_formatPercent: formatPercent()
  participant_formatPercent-->>participant_analyzeBadges: return
  participant_analyzeBadges->>participant_getCoverageColor: getCoverageColor()
  participant_getCoverageColor-->>participant_analyzeBadges: return
  participant_analyzeBadges->>participant_sortBadges: sortBadges()
  participant_sortBadges-->>participant_analyzeBadges: return
  participant_analyzeBadges-->>participant_analyze: return
  participant_analyze->>participant_createProject: createProject()
  participant_createProject-->>participant_analyze: return
  participant_analyze->>participant_createTypeScriptProgram: createTypeScriptProgram()
  participant_createTypeScriptProgram-->>participant_analyze: return
  participant_analyze->>participant_analyzeExports: analyzeExports()
  participant_analyzeExports->>participant_getEntryPointSourceFiles: getEntryPointSourceFiles()
  participant_getEntryPointSourceFiles-->>participant_analyzeExports: return
  participant_analyzeExports->>participant_toPosixPath: toPosixPath()
  participant_toPosixPath-->>participant_analyzeExports: return
  participant_analyzeExports->>participant_relative: relative()
  participant_relative-->>participant_analyzeExports: return
  participant_analyzeExports->>participant_resolveExportSymbol: resolveExportSymbol()
  participant_resolveExportSymbol-->>participant_analyzeExports: return
  participant_analyzeExports->>participant_getFirstDeclaration: getFirstDeclaration()
  participant_getFirstDeclaration-->>participant_analyzeExports: return
  participant_analyzeExports->>participant_getParadoxComment: getParadoxComment()
  participant_getParadoxComment-->>participant_analyzeExports: return
  participant_analyzeExports->>participant_parseParadoxComment: parseParadoxComment()
  participant_parseParadoxComment-->>participant_analyzeExports: return
  participant_analyzeExports->>participant_createEmptyMetadata: createEmptyMetadata()
  participant_createEmptyMetadata-->>participant_analyzeExports: return
  participant_analyzeExports->>participant_getExportMetadata: getExportMetadata()
  participant_getExportMetadata->>participant_toPosixPath: toPosixPath()
  participant_toPosixPath-->>participant_getExportMetadata: return
  participant_getExportMetadata->>participant_relative: relative()
  participant_relative-->>participant_getExportMetadata: return
  participant_getExportMetadata->>participant_getSourceLocation: getSourceLocation()
  participant_getSourceLocation->>participant_toPosixPath: toPosixPath()
  participant_toPosixPath-->>participant_getSourceLocation: return
  participant_getSourceLocation->>participant_relative: relative()
  participant_relative-->>participant_getSourceLocation: return
  participant_getSourceLocation-->>participant_getExportMetadata: return
  participant_getExportMetadata->>participant_getSignatures: getSignatures()
  participant_getSignatures->>participant_readParadoxMetadata: readParadoxMetadata()
  participant_readParadoxMetadata->>participant_getParadoxComment: getParadoxComment()
  participant_getParadoxComment-->>participant_readParadoxMetadata: return
  participant_readParadoxMetadata->>participant_parseParadoxComment: parseParadoxComment()
  participant_parseParadoxComment-->>participant_readParadoxMetadata: return
  participant_readParadoxMetadata-->>participant_getSignatures: return
  participant_getSignatures->>participant_getCallableDeclarations: getCallableDeclarations()
  participant_getCallableDeclarations->>participant_getCallableNode: getCallableNode()
  participant_getCallableNode-->>participant_getCallableDeclarations: return
  participant_getCallableDeclarations-->>participant_getSignatures: return
  participant_getSignatures->>participant_uniqueBy: uniqueBy()
  participant_uniqueBy-->>participant_getSignatures: return
  participant_getSignatures-->>participant_getExportMetadata: return
  participant_getExportMetadata->>participant_getMembers: getMembers()
  participant_getMembers->>participant_getCallableNode: getCallableNode()
  participant_getCallableNode-->>participant_getMembers: return
  participant_getMembers->>participant_getMembersFromProperties: getMembersFromProperties()
  participant_getMembersFromProperties-->>participant_getMembers: return
  participant_getMembers-->>participant_getExportMetadata: return
  participant_getExportMetadata->>participant_collectRelatedSymbols: collectRelatedSymbols()
  participant_collectRelatedSymbols-->>participant_getExportMetadata: return
  participant_getExportMetadata-->>participant_analyzeExports: return
  participant_analyzeExports->>participant_uniqueSorted: uniqueSorted()
  participant_uniqueSorted-->>participant_analyzeExports: return
  participant_analyzeExports->>participant_inferKind: inferKind()
  participant_inferKind-->>participant_analyzeExports: return
  participant_analyzeExports-->>participant_analyze: return
  participant_analyze->>participant_analyzeComponents: analyzeComponents()
  participant_analyzeComponents->>participant_isReactComponent: isReactComponent()
  participant_isReactComponent-->>participant_analyzeComponents: return
  participant_analyzeComponents->>participant_collectPropsForExport: collectPropsForExport()
  participant_collectPropsForExport-->>participant_analyzeComponents: return
  participant_analyzeComponents->>participant_getComponentPropsType: getComponentPropsType()
  participant_getComponentPropsType->>participant_getCallSignature: getCallSignature()
  participant_getCallSignature-->>participant_getComponentPropsType: return
  participant_getComponentPropsType-->>participant_analyzeComponents: return
  participant_analyzeComponents->>participant_getPropsFromType: getPropsFromType()
  participant_getPropsFromType-->>participant_analyzeComponents: return
  participant_analyzeComponents-->>participant_analyze: return
  participant_analyze->>participant_analyzeModules: analyzeModules()
  participant_analyzeModules->>participant_normalize: normalize()
  participant_normalize-->>participant_analyzeModules: return
  participant_analyzeModules-->>participant_analyze: return
  participant_analyze->>participant_collectTypeMembers: collectTypeMembers()
  participant_collectTypeMembers-->>participant_analyze: return
  participant_analyze->>participant_resolveTypeReference: resolveTypeReference()
  participant_resolveTypeReference-->>participant_analyze: return
  participant_analyze->>participant_collectImportGraph: collectImportGraph()
  participant_collectImportGraph-->>participant_analyze: return
  participant_analyze->>participant_collectCallGraph: collectCallGraph()
  participant_collectCallGraph-->>participant_analyze: return
  participant_analyze->>participant_collectComponentCompositionGraph: collectComponentCompositionGraph()
  participant_collectComponentCompositionGraph-->>participant_analyze: return
  participant_analyze->>participant_mapTypeMembers: mapTypeMembers()
  participant_mapTypeMembers-->>participant_analyze: return
  participant_analyze-->>participant_main: return
  participant_main->>participant_buildModel: buildModel()
  participant_buildModel->>participant_sortByName: sortByName()
  participant_sortByName-->>participant_buildModel: return
  participant_buildModel->>participant_getDefaultConfigFileName: getDefaultConfigFileName()
  participant_getDefaultConfigFileName-->>participant_buildModel: return
  participant_buildModel->>participant_findConfigFactoryName: findConfigFactoryName()
  participant_findConfigFactoryName-->>participant_buildModel: return
  participant_buildModel-->>participant_main: return
  participant_main->>participant_render: render()
  participant_render->>participant_renderBadgeArtifacts: renderBadgeArtifacts()
  participant_renderBadgeArtifacts-->>participant_render: return
  participant_render->>participant_renderDiagramArtifacts: renderDiagramArtifacts()
  participant_renderDiagramArtifacts->>participant_renderArchitectureOverview: renderArchitectureOverview()
  participant_renderArchitectureOverview->>participant_toMermaidId: toMermaidId()
  participant_toMermaidId-->>participant_renderArchitectureOverview: return
  participant_renderArchitectureOverview->>participant_escapeLabel: escapeLabel()
  participant_escapeLabel-->>participant_renderArchitectureOverview: return
  participant_renderArchitectureOverview-->>participant_renderDiagramArtifacts: return
  participant_renderDiagramArtifacts->>participant_renderModuleRelationships: renderModuleRelationships()
  participant_renderModuleRelationships->>participant_toMermaidId: toMermaidId()
  participant_toMermaidId-->>participant_renderModuleRelationships: return
  participant_renderModuleRelationships->>participant_escapeLabel: escapeLabel()
  participant_escapeLabel-->>participant_renderModuleRelationships: return
  participant_renderModuleRelationships->>participant_renderFallbackEdge: renderFallbackEdge()
  participant_renderFallbackEdge-->>participant_renderModuleRelationships: return
  participant_renderModuleRelationships-->>participant_renderDiagramArtifacts: return
  participant_renderDiagramArtifacts->>participant_renderExportGraph: renderExportGraph()
  participant_renderExportGraph->>participant_toMermaidId: toMermaidId()
  participant_toMermaidId-->>participant_renderExportGraph: return
  participant_renderExportGraph->>participant_escapeLabel: escapeLabel()
  participant_escapeLabel-->>participant_renderExportGraph: return
  participant_renderExportGraph-->>participant_renderDiagramArtifacts: return
  participant_renderDiagramArtifacts->>participant_renderEntrypointSequence: renderEntrypointSequence()
  participant_renderEntrypointSequence->>participant_toMermaidId: toMermaidId()
  participant_toMermaidId-->>participant_renderEntrypointSequence: return
  participant_renderEntrypointSequence->>participant_escapeLabel: escapeLabel()
  participant_escapeLabel-->>participant_renderEntrypointSequence: return
  participant_renderEntrypointSequence->>participant_collectReachableCallEdges: collectReachableCallEdges()
  participant_collectReachableCallEdges->>participant_groupCallsBySource: groupCallsBySource()
  participant_groupCallsBySource-->>participant_collectReachableCallEdges: return
  participant_collectReachableCallEdges->>participant_getCallFlowRoots: getCallFlowRoots()
  participant_getCallFlowRoots->>participant_uniqueSorted: uniqueSorted()
  participant_uniqueSorted-->>participant_getCallFlowRoots: return
  participant_getCallFlowRoots-->>participant_collectReachableCallEdges: return
  participant_collectReachableCallEdges->>participant_visitCallEdges: visitCallEdges()
  participant_visitCallEdges->>participant_getCallEdgeKey: getCallEdgeKey()
  participant_getCallEdgeKey-->>participant_visitCallEdges: return
  participant_visitCallEdges->>participant_visitCallEdges: visitCallEdges()
  participant_visitCallEdges-->>participant_visitCallEdges: return
  participant_visitCallEdges-->>participant_collectReachableCallEdges: return
  participant_collectReachableCallEdges-->>participant_renderEntrypointSequence: return
  participant_renderEntrypointSequence->>participant_collectSequenceParticipants: collectSequenceParticipants()
  participant_collectSequenceParticipants->>participant_uniqueSorted: uniqueSorted()
  participant_uniqueSorted-->>participant_collectSequenceParticipants: return
  participant_collectSequenceParticipants-->>participant_renderEntrypointSequence: return
  participant_renderEntrypointSequence->>participant_renderCallFlow: renderCallFlow()
  participant_renderCallFlow->>participant_groupCallsBySource: groupCallsBySource()
  participant_groupCallsBySource-->>participant_renderCallFlow: return
  participant_renderCallFlow->>participant_getCallFlowRoots: getCallFlowRoots()
  participant_getCallFlowRoots-->>participant_renderCallFlow: return
  participant_renderCallFlow->>participant_renderNestedCalls: renderNestedCalls()
  participant_renderNestedCalls->>participant_getCallEdgeKey: getCallEdgeKey()
  participant_getCallEdgeKey-->>participant_renderNestedCalls: return
  participant_renderNestedCalls->>participant_toMermaidId: toMermaidId()
  participant_toMermaidId-->>participant_renderNestedCalls: return
  participant_renderNestedCalls->>participant_formatCallLabel: formatCallLabel()
  participant_formatCallLabel-->>participant_renderNestedCalls: return
  participant_renderNestedCalls->>participant_renderNestedCalls: renderNestedCalls()
  participant_renderNestedCalls-->>participant_renderNestedCalls: return
  participant_renderNestedCalls-->>participant_renderCallFlow: return
  participant_renderCallFlow-->>participant_renderEntrypointSequence: return
  participant_renderEntrypointSequence-->>participant_renderDiagramArtifacts: return
  participant_renderDiagramArtifacts-->>participant_render: return
  participant_render->>participant_renderer: renderer()
  participant_renderer-->>participant_render: return
  participant_render-->>participant_main: return
  participant_main->>participant_write: write()
  participant_write->>participant_mkdir: mkdir()
  participant_mkdir-->>participant_write: return
  participant_write->>participant_writeFile: writeFile()
  participant_writeFile-->>participant_write: return
  participant_write->>participant_join: join()
  participant_join-->>participant_write: return
  participant_write->>participant_dirname: dirname()
  participant_dirname-->>participant_write: return
  participant_write-->>participant_main: return
  participant_main-->>participant_src_cli_ts: return
  participant_src_model_buildModel_ts->>participant_mapExport: mapExport()
  participant_mapExport->>participant_sortByName: sortByName()
  participant_sortByName-->>participant_mapExport: return
  participant_mapExport-->>participant_src_model_buildModel_ts: return
  participant_src_model_buildModel_ts->>participant_mapComponent: mapComponent()
  participant_mapComponent->>participant_sortByName: sortByName()
  participant_sortByName-->>participant_mapComponent: return
  participant_mapComponent-->>participant_src_model_buildModel_ts: return
  participant_src_model_buildModel_ts->>participant_sortByName: sortByName()
  participant_sortByName-->>participant_src_model_buildModel_ts: return
  participant_src_render_renderers_badges_ts->>participant_renderBadgeSvg: renderBadgeSvg()
  participant_renderBadgeSvg->>participant_getTextWidth: getTextWidth()
  participant_getTextWidth-->>participant_renderBadgeSvg: return
  participant_renderBadgeSvg->>participant_escapeXml: escapeXml()
  participant_escapeXml-->>participant_renderBadgeSvg: return
  participant_renderBadgeSvg-->>participant_src_render_renderers_badges_ts: return
  participant_src_render_renderers_diagrams_ts->>participant_toMermaidId: toMermaidId()
  participant_toMermaidId-->>participant_src_render_renderers_diagrams_ts: return
  participant_src_render_renderers_html_ts->>participant_toAnchorId: toAnchorId()
  participant_toAnchorId-->>participant_src_render_renderers_html_ts: return
  participant_src_render_renderers_html_ts->>participant_escapeAttribute: escapeAttribute()
  participant_escapeAttribute-->>participant_src_render_renderers_html_ts: return
  participant_src_render_renderers_html_ts->>participant_escapeHtml: escapeHtml()
  participant_escapeHtml-->>participant_src_render_renderers_html_ts: return
  participant_src_render_renderers_html_ts->>participant_renderExportCard: renderExportCard()
  participant_renderExportCard->>participant_toAnchorId: toAnchorId()
  participant_toAnchorId-->>participant_renderExportCard: return
  participant_renderExportCard->>participant_escapeAttribute: escapeAttribute()
  participant_escapeAttribute-->>participant_renderExportCard: return
  participant_renderExportCard->>participant_escapeHtml: escapeHtml()
  participant_escapeHtml-->>participant_renderExportCard: return
  participant_renderExportCard->>participant_renderInlineCodeList: renderInlineCodeList()
  participant_renderInlineCodeList-->>participant_renderExportCard: return
  participant_renderExportCard->>participant_renderChipList: renderChipList()
  participant_renderChipList-->>participant_renderExportCard: return
  participant_renderExportCard->>participant_renderSignatureBlock: renderSignatureBlock()
  participant_renderSignatureBlock-->>participant_renderExportCard: return
  participant_renderExportCard->>participant_renderMemberTable: renderMemberTable()
  participant_renderMemberTable-->>participant_renderExportCard: return
  participant_renderExportCard-->>participant_src_render_renderers_html_ts: return
  participant_src_render_renderers_markdown_ts->>participant_badgeLabel: badgeLabel()
  participant_badgeLabel-->>participant_src_render_renderers_markdown_ts: return
  participant_src_render_renderers_markdown_ts->>participant_sortReadmeItems: sortReadmeItems()
  participant_sortReadmeItems-->>participant_src_render_renderers_markdown_ts: return
  participant_src_render_renderers_markdown_ts->>participant_getReadmeItemName: getReadmeItemName()
  participant_getReadmeItemName-->>participant_src_render_renderers_markdown_ts: return
  participant_src_render_renderers_markdown_ts->>participant_flattenConfigMembers: flattenConfigMembers()
  participant_flattenConfigMembers-->>participant_src_render_renderers_markdown_ts: return
