graph LR
  module_src_config_ts["src/config.ts"]
  module_src_index_ts["src/index.ts"]
  module_src_internal_ts["src/internal.ts"]
  module_src_ui_ts["src/ui.ts"]
  module_src_config_ts -.-> module_src_index_ts
  module_src_index_ts -.-> module_src_internal_ts
  module_src_internal_ts -.-> module_src_ui_ts
